# Generated by Django 4.2.7 on 2026-04-03 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datapipeline', '0012_feedbackgpt_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackgpt',
            name='anonymity_mode',
            field=models.CharField(choices=[('anonymous', 'Anonymous'), ('pseudonymous', 'Pseudonymous'), ('identified', 'Identified')], default='anonymous', max_length=20),
        ),
        migrations.AddField(
            model_name='feedbackgpt',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedbackgpt',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feedbackgpt',
            name='opens_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedbackgpt',
            name='reporting_structure',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='feedbackgpt',
            name='survey_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('group', 'Group')], default='individual', max_length=20),
        ),
        migrations.AddField(
            model_name='feedbackgpt',
            name='themes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='feedbackgpt',
            name='timing_category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
