# Generated by Django 4.2.7 on 2026-04-09 07:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('datapipeline', '0018_remove_feedbackgpt_survey_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='LEAIChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='New chat', max_length=120)),
                ('scope_kind', models.CharField(choices=[('course', 'course'), ('week', 'week'), ('custom', 'custom')], default='course', max_length=16)),
                ('scope_week_number', models.IntegerField(blank=True, null=True)),
                ('scope_survey_ids', models.JSONField(blank=True, default=list)),
                ('scope_session_ids', models.JSONField(blank=True, default=list)),
                ('system_prompt_override', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leai_chat_sessions', to='datapipeline.course')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='LEAIChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'user'), ('assistant', 'assistant'), ('system', 'system')], max_length=16)),
                ('text', models.TextField()),
                ('cited', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='datapipeline.leaichatsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='LEAIQuickTake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_key', models.CharField(max_length=64)),
                ('bullets', models.JSONField(default=list)),
                ('verification', models.JSONField(default=list)),
                ('system_prompt', models.TextField()),
                ('user_text', models.TextField()),
                ('model_name', models.CharField(default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leai_quicktakes', to='datapipeline.course')),
            ],
            options={
                'indexes': [models.Index(fields=['course', 'scope_key'], name='datapipelin_course__d7dff7_idx')],
                'unique_together': {('course', 'scope_key')},
            },
        ),
        migrations.AddIndex(
            model_name='leaichatsession',
            index=models.Index(fields=['course', '-updated_at'], name='datapipelin_course__eca04c_idx'),
        ),
        migrations.AddIndex(
            model_name='leaichatmessage',
            index=models.Index(fields=['session', 'created_at'], name='datapipelin_session_f62069_idx'),
        ),
    ]
