# Generated by Django 4.2.7 on 2026-04-17 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datapipeline', '0020_leaiquicktake_async_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackgpt',
            name='mode',
            field=models.CharField(choices=[('general', 'General course feedback'), ('group', 'In-group team feedback')], default='general', max_length=16),
        ),
        migrations.CreateModel(
            name='TeamConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('label_prefix', models.CharField(default='Team', max_length=50)),
                ('color', models.CharField(choices=[('forest', 'forest'), ('plum', 'plum'), ('amber', 'amber'), ('teal', 'teal'), ('rose', 'rose'), ('indigo', 'indigo'), ('brown', 'brown'), ('slate', 'slate')], default='forest', max_length=16)),
                ('archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_configurations', to='datapipeline.course')),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('course', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SurveyTeamSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('label_prefix', models.CharField(default='Team', max_length=50)),
                ('color', models.CharField(choices=[('forest', 'forest'), ('plum', 'plum'), ('amber', 'amber'), ('teal', 'teal'), ('rose', 'rose'), ('indigo', 'indigo'), ('brown', 'brown'), ('slate', 'slate')], default='forest', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_configuration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshots', to='datapipeline.teamconfiguration')),
                ('survey', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team_snapshot', to='datapipeline.feedbackgpt')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('size', models.IntegerField()),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='datapipeline.surveyteamsnapshot')),
            ],
            options={
                'ordering': ['number'],
                'unique_together': {('snapshot', 'number')},
            },
        ),
        migrations.CreateModel(
            name='SessionTeamAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('survey_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='datapipeline.surveyteam')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('size', models.IntegerField()),
                ('team_configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='datapipeline.teamconfiguration')),
            ],
            options={
                'ordering': ['number'],
                'unique_together': {('team_configuration', 'number')},
            },
        ),
    ]
