# Generated by Django 4.2.7 on 2026-05-04 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datapipeline', '0021_feedbackgpt_mode_teamconfiguration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_id', models.CharField(max_length=64, unique=True)),
                ('version', models.CharField(default='1.0.0', max_length=16)),
                ('title', models.CharField(default='', max_length=200)),
                ('course_label', models.CharField(blank=True, default='', max_length=100)),
                ('week_number', models.IntegerField(blank=True, null=True)),
                ('body', models.JSONField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['course_label', 'week_number', 'schema_id'],
            },
        ),
        migrations.AlterField(
            model_name='feedbackgpt',
            name='mode',
            field=models.CharField(choices=[('general', 'General course feedback'), ('group', 'In-group team feedback'), ('form', 'Form-mapped structured reflection')], default='general', max_length=16),
        ),
        migrations.AddField(
            model_name='feedbackgpt',
            name='form_schema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surveys', to='datapipeline.formschema'),
        ),
    ]
