# Generated by Django 4.2.7 on 2026-05-13 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datapipeline', '0026_team_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaiquicktake',
            name='gaps',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='leaiquicktake',
            name='tensions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
