# Generated by Django 4.2.7 on 2026-05-13 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datapipeline', '0027_leaiquicktake_tensions_gaps'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaiquicktake',
            name='team_health',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
