# Generated by Django 4.2.7 on 2026-05-13 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datapipeline', '0028_leaiquicktake_team_health'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaiquicktake',
            name='form_sections',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
