# Generated by Django 4.2.7 on 2026-05-15 02:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('datapipeline', '0030_leaichatmessage_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackmessage',
            name='source',
            field=models.CharField(choices=[('chat', 'Chat'), ('pdf', 'PDF')], default='chat', max_length=8),
        ),
        migrations.CreateModel(
            name='LEAIPdfIngestBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('committed_by', models.CharField(blank=True, default='', max_length=100)),
                ('student_count', models.IntegerField(default=0)),
                ('message_count', models.IntegerField(default=0)),
                ('items_summary', models.JSONField(default=list)),
                ('reverted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_ingest_batches', to='datapipeline.feedbackgpt')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='feedbackmessage',
            name='pdf_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='datapipeline.leaipdfingestbatch'),
        ),
        migrations.CreateModel(
            name='LEAIPdfIngestJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_by', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('items', models.JSONField(default=list)),
                ('progress', models.JSONField(default=dict)),
                ('error', models.TextField(blank=True, default='')),
                ('job_started_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_ingest_jobs', to='datapipeline.feedbackgpt')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['survey', '-created_at'], name='datapipelin_survey__c52f47_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='leaipdfingestbatch',
            index=models.Index(fields=['survey', '-created_at'], name='datapipelin_survey__0f0423_idx'),
        ),
    ]
