# Generated by Django 4.2.7 on 2026-05-28 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datapipeline', '0032_fix_team_reflection_closing_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaiquicktake',
            name='actions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='leaiquicktake',
            name='responses_count_at_generation',
            field=models.IntegerField(default=0),
        ),
    ]
