# Generated by Django 4.2.7 on 2026-06-13 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datapipeline', '0033_leaiquicktake_actions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='banner_dismissible',
            field=models.BooleanField(default=False, help_text='Whether students can close the banner.'),
        ),
        migrations.AddField(
            model_name='course',
            name='banner_display_mode',
            field=models.CharField(choices=[('persistent', 'Persistent'), ('timed', 'Auto-dismiss after duration')], default='persistent', max_length=16),
        ),
        migrations.AddField(
            model_name='course',
            name='banner_duration_seconds',
            field=models.PositiveIntegerField(default=10, help_text="Seconds before auto-dismiss when display mode is 'timed'."),
        ),
        migrations.AddField(
            model_name='course',
            name='banner_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='banner_text',
            field=models.TextField(blank=True, default='', help_text='Message shown to students. Leave blank to use the default disclaimer.'),
        ),
    ]
