# Generated by Django 4.2.7 on 2026-06-14 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datapipeline', '0034_course_banner_dismissible_course_banner_display_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='banner_split_enabled',
            field=models.BooleanField(default=False, help_text='When on, only a random subset of students see the banner (A/B).'),
        ),
        migrations.AddField(
            model_name='course',
            name='banner_split_mode',
            field=models.CharField(choices=[('percentage', 'Percentage of students'), ('count', 'Fixed number of students')], default='percentage', max_length=16),
        ),
        migrations.AddField(
            model_name='course',
            name='banner_split_value',
            field=models.PositiveIntegerField(default=50, help_text='Percent (0-100) in percentage mode, or number of students in count mode.'),
        ),
        migrations.CreateModel(
            name='BannerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
                ('shown', models.BooleanField()),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banner_assignments', to='datapipeline.course')),
            ],
            options={
                'indexes': [models.Index(fields=['course', 'session_id'], name='datapipelin_course__51e2de_idx')],
                'unique_together': {('course', 'session_id')},
            },
        ),
    ]
