# Generated by Django 4.2.7 on 2026-06-24 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datapipeline', '0035_course_banner_split_enabled_course_banner_split_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='bot_display_name',
            field=models.CharField(blank=True, default='', help_text="Name shown on the AI's message tag in student chats. Blank uses the default 'LEAI'.", max_length=100),
        ),
    ]
