# Generated by Django 4.2.7 on 2026-07-17 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datapipeline', '0037_fix_cmpm80h_closing_prompts'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='referral_enabled',
            field=models.BooleanField(default=False, help_text='Let the chat point struggling students to a human, once per conversation.'),
        ),
        migrations.AddField(
            model_name='course',
            name='referral_text',
            field=models.CharField(blank=True, default='', help_text="Where the bot points them. Blank uses the default 'your instructor or TA during their office hours'.", max_length=200),
        ),
    ]
