# Generated by Django 4.2.7 on 2026-07-29 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datapipeline', '0038_course_referral_enabled_course_referral_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackmessage',
            name='referred',
            field=models.BooleanField(default=False),
        ),
    ]
