# Generated by Django 4.2.7 on 2026-08-05 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datapipeline', '0039_feedbackmessage_referred'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='identity_tracking_enabled',
            field=models.BooleanField(default=False, help_text="Silently link one student's sessions across weeks via device signals."),
        ),
        migrations.CreateModel(
            name='SessionIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
                ('device_key', models.CharField(blank=True, default='', max_length=64)),
                ('fingerprint', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_identities', to='datapipeline.course')),
            ],
            options={
                'indexes': [models.Index(fields=['course', 'device_key'], name='datapipelin_course__2471b1_idx'), models.Index(fields=['course', 'fingerprint'], name='datapipelin_course__a39bd2_idx')],
                'unique_together': {('course', 'session_id')},
            },
        ),
    ]
