# Generated by Django 4.2.7 on 2026-09-10 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('datapipeline', '0044_feedbackmessage_form_attribution'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('instructor', 'Instructor'), ('ta', 'Teaching assistant')], max_length=20)),
                ('can_publish', models.BooleanField(default=False)),
                ('can_export', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['course__course_id', 'role', 'institution_membership_id'],
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='InstructorAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('display_name', models.CharField(max_length=200)),
                ('auth_provider', models.CharField(choices=[('manual', 'Manual'), ('cognito', 'Amazon Cognito')], default='manual', max_length=20)),
                ('external_subject', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('must_change_password', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='leai_instructor_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['email'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='legacy_password_login_enabled',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='LegacyCourseOwnershipReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('linked', 'Linked'), ('ambiguous', 'Ambiguous'), ('unresolved', 'Unresolved')], max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ownership_review', to='datapipeline.course')),
                ('linked_membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='legacy_ownership_reviews', to='datapipeline.coursemembership')),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('member', 'Member'), ('admin', 'Institution administrator')], default='member', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='datapipeline.institution')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='institution_memberships', to='datapipeline.instructoraccount')),
            ],
            options={
                'ordering': ['institution__name', 'instructor__email'],
            },
        ),
        migrations.AddField(
            model_name='coursemembership',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='datapipeline.course'),
        ),
        migrations.AddField(
            model_name='coursemembership',
            name='institution_membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_memberships', to='datapipeline.institutionmembership'),
        ),
        migrations.AddField(
            model_name='course',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='datapipeline.institution'),
        ),
        migrations.CreateModel(
            name='InstructorSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_digest', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='datapipeline.instructoraccount')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['instructor', 'revoked_at', 'expires_at'], name='datapipelin_instruc_1abccd_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='institutionmembership',
            constraint=models.UniqueConstraint(fields=('institution', 'instructor'), name='leai_unique_institution_instructor'),
        ),
        migrations.AddConstraint(
            model_name='coursemembership',
            constraint=models.UniqueConstraint(fields=('course', 'institution_membership'), name='leai_unique_course_institution_membership'),
        ),
        migrations.AddConstraint(
            model_name='coursemembership',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('role', 'owner')), fields=('course',), name='leai_one_active_course_owner'),
        ),
        migrations.AlterField(
            model_name='course',
            name='legacy_password_login_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
