# Generated by Django 4.2.7 on 2026-09-10 22:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('datapipeline', '0045_instructor_identity_foundation'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('course_id_snapshot', models.CharField(blank=True, default='', max_length=50)),
                ('action', models.CharField(choices=[('auth.login_succeeded', 'Login succeeded'), ('auth.login_denied', 'Login denied'), ('auth.logout', 'Logout'), ('account.password_changed', 'Password changed'), ('account.profile_updated', 'Profile updated'), ('course.created', 'Course created'), ('course.banner_updated', 'Course banner updated'), ('course.customization_updated', 'Course customization updated'), ('survey.created', 'Survey created'), ('survey.updated', 'Survey updated'), ('survey.status_changed', 'Survey status changed'), ('survey.cloned', 'Survey cloned'), ('survey.deleted', 'Survey deleted'), ('survey.responses_exported', 'Survey responses exported'), ('analysis.session_created', 'Analysis session created'), ('analysis.session_updated', 'Analysis session updated'), ('analysis.session_deleted', 'Analysis session deleted'), ('analysis.turn_started', 'Analysis turn started'), ('analysis.quicktake_generated', 'Analysis quick take generated'), ('analysis.quicktake_deleted', 'Analysis quick take deleted'), ('team_configuration.created', 'Team configuration created'), ('team_configuration.updated', 'Team configuration updated'), ('team_configuration.archived', 'Team configuration archived'), ('team_configuration.deleted', 'Team configuration deleted'), ('pdf_ingest.started', 'PDF ingest started'), ('pdf_ingest.abandoned', 'PDF ingest abandoned'), ('pdf_ingest.committed', 'PDF ingest committed'), ('pdf_ingest.reverted', 'PDF ingest reverted'), ('authorization.denied', 'Authorization denied')], max_length=64)),
                ('outcome', models.CharField(choices=[('success', 'Success'), ('denied', 'Denied'), ('failed', 'Failed')], max_length=16)),
                ('target_type', models.CharField(blank=True, default='', max_length=32)),
                ('target_id', models.CharField(blank=True, default='', max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='datapipeline.instructoraccount')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructor_audit_events', to='datapipeline.course')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='datapipeline.instructorsession')),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
                'indexes': [models.Index(fields=['actor', '-occurred_at'], name='leai_audit_actor_time'), models.Index(fields=['course', '-occurred_at'], name='leai_audit_course_time'), models.Index(fields=['action', 'outcome', '-occurred_at'], name='leai_audit_action_time')],
            },
        ),
    ]
