# Generated by Django 4.2.7 on 2026-09-11 03:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('datapipeline', '0046_instructorauditevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('client_session_id', models.CharField(max_length=100)),
                ('source', models.CharField(choices=[('student', 'Student chat'), ('pdf', 'PDF import')], default='student', max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('next_message_sequence', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='feedbackmessage',
            name='sequence',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='responsesession',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='response_sessions', to='datapipeline.course'),
        ),
        migrations.AddField(
            model_name='responsesession',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_sessions', to='datapipeline.feedbackgpt'),
        ),
        migrations.AddField(
            model_name='feedbackmessage',
            name='response_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='datapipeline.responsesession'),
        ),
        migrations.AddConstraint(
            model_name='feedbackmessage',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('response_session__isnull', True), ('sequence__isnull', True)), models.Q(('response_session__isnull', False), ('sequence__isnull', False)), _connector='OR'), name='leai_message_session_sequence_pair'),
        ),
        migrations.AddConstraint(
            model_name='feedbackmessage',
            constraint=models.UniqueConstraint(condition=models.Q(('response_session__isnull', False)), fields=('response_session', 'sequence'), name='leai_unique_session_message_sequence'),
        ),
        migrations.AddIndex(
            model_name='responsesession',
            index=models.Index(fields=['course', '-started_at'], name='leai_response_course_time'),
        ),
        migrations.AddConstraint(
            model_name='responsesession',
            constraint=models.UniqueConstraint(fields=('survey', 'client_session_id'), name='leai_unique_survey_client_session'),
        ),
    ]
