# Generated by Django 4.2.7 on 2026-09-10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('datapipeline', '0047_responsesession_feedbackmessage_sequence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructorauditevent',
            name='action',
            field=models.CharField(choices=[('auth.login_succeeded', 'Login succeeded'), ('auth.login_denied', 'Login denied'), ('auth.logout', 'Logout'), ('account.password_changed', 'Password changed'), ('account.profile_updated', 'Profile updated'), ('course.created', 'Course created'), ('course.banner_updated', 'Course banner updated'), ('course.customization_updated', 'Course customization updated'), ('survey.created', 'Survey created'), ('survey.updated', 'Survey updated'), ('survey.status_changed', 'Survey status changed'), ('survey.cloned', 'Survey cloned'), ('survey.deleted', 'Survey deleted'), ('survey.responses_exported', 'Survey responses exported'), ('analysis.session_created', 'Analysis session created'), ('analysis.session_updated', 'Analysis session updated'), ('analysis.session_deleted', 'Analysis session deleted'), ('analysis.turn_started', 'Analysis turn started'), ('analysis.quicktake_generated', 'Analysis quick take generated'), ('analysis.quicktake_deleted', 'Analysis quick take deleted'), ('team_configuration.created', 'Team configuration created'), ('team_configuration.updated', 'Team configuration updated'), ('team_configuration.archived', 'Team configuration archived'), ('team_configuration.deleted', 'Team configuration deleted'), ('pdf_ingest.started', 'PDF ingest started'), ('pdf_ingest.abandoned', 'PDF ingest abandoned'), ('pdf_ingest.committed', 'PDF ingest committed'), ('pdf_ingest.reverted', 'PDF ingest reverted'), ('question_set.draft_created', 'Question set draft created'), ('question_set.draft_saved', 'Question set draft saved'), ('question_set.revision_frozen', 'Question set revision frozen'), ('question_set.preview_started', 'Question set preview started'), ('question_set.preview_completed', 'Question set preview completed'), ('authorization.denied', 'Authorization denied')], max_length=64),
        ),
        migrations.CreateModel(
            name='QuestionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('template_id', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=200)),
                ('audience', models.CharField(choices=[('individual', 'Individual structured reflection')], default='individual', max_length=20)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_sets', to='datapipeline.course')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_question_sets', to='datapipeline.instructoraccount')),
            ],
            options={'ordering': ['-updated_at', '-id']},
        ),
        migrations.CreateModel(
            name='QuestionSetRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('revision_number', models.PositiveIntegerField()),
                ('source_draft_version', models.PositiveIntegerField()),
                ('canonical_body', models.JSONField()),
                ('compiled_protocol', models.JSONField()),
                ('content_hash', models.CharField(max_length=64)),
                ('compiler_version', models.CharField(default='1', max_length=32)),
                ('engine_version', models.CharField(default='formmode-v1', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_question_set_revisions', to='datapipeline.instructoraccount')),
                ('question_set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='datapipeline.questionset')),
            ],
            options={'ordering': ['question_set_id', 'revision_number']},
        ),
        migrations.CreateModel(
            name='QuestionSetDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('body', models.JSONField()),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='based_drafts', to='datapipeline.questionsetrevision')),
                ('question_set', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='draft', to='datapipeline.questionset')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_question_set_drafts', to='datapipeline.instructoraccount')),
            ],
            options={'ordering': ['-updated_at', '-id']},
        ),
        migrations.CreateModel(
            name='QuestionSetValidationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_valid', models.BooleanField()),
                ('result', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('draft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='validation_runs', to='datapipeline.questionsetdraft')),
                ('revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='validation_runs', to='datapipeline.questionsetrevision')),
            ],
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.CreateModel(
            name='PreviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('token_digest', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('next_message_sequence', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_set_preview_sessions', to='datapipeline.instructoraccount')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preview_sessions', to='datapipeline.questionsetrevision')),
            ],
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.CreateModel(
            name='PreviewMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=16)),
                ('content', models.TextField()),
                ('attribution', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('preview_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='datapipeline.previewsession')),
            ],
            options={'ordering': ['sequence', 'id']},
        ),
        migrations.CreateModel(
            name='QuestionSetSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_question_set_surveys', to='datapipeline.instructoraccount')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='survey_links', to='datapipeline.questionsetrevision')),
                ('survey', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='question_set_link', to='datapipeline.feedbackgpt')),
            ],
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.AddIndex(
            model_name='questionset',
            index=models.Index(fields=['course', 'archived_at', '-updated_at'], name='leai_qset_course_active'),
        ),
        migrations.AddConstraint(
            model_name='questionsetrevision',
            constraint=models.UniqueConstraint(fields=('question_set', 'revision_number'), name='leai_unique_qset_revision_number'),
        ),
        migrations.AddConstraint(
            model_name='questionsetrevision',
            constraint=models.UniqueConstraint(fields=('question_set', 'content_hash'), name='leai_unique_qset_revision_hash'),
        ),
        migrations.AddConstraint(
            model_name='questionsetvalidationrun',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('draft__isnull', False), ('revision__isnull', True)), models.Q(('draft__isnull', True), ('revision__isnull', False)), _connector='OR'), name='leai_validation_one_source'),
        ),
        migrations.AddIndex(
            model_name='previewsession',
            index=models.Index(fields=['revision', 'completed_at'], name='leai_preview_revision_done'),
        ),
        migrations.AddConstraint(
            model_name='previewmessage',
            constraint=models.UniqueConstraint(fields=('preview_session', 'sequence'), name='leai_unique_preview_message_sequence'),
        ),
    ]
