# Generated by Django 4.2.7 on 2026-09-13

from django.db import migrations, models


def normalize_question_set_workflows(apps, schema_editor):
    QuestionSet = apps.get_model('datapipeline', 'QuestionSet')
    QuestionSetSurvey = apps.get_model('datapipeline', 'QuestionSetSurvey')

    published_ids = QuestionSetSurvey.objects.values_list(
        'revision__question_set_id',
        flat=True,
    ).distinct()
    QuestionSet.objects.filter(pk__in=published_ids).update(
        workflow_status='completed',
    )

    eligible = (
        QuestionSet.objects
        .filter(archived_at__isnull=True, draft__isnull=False)
        .exclude(revisions__survey_links__isnull=False)
    )
    for course_id in eligible.values_list('course_id', flat=True).distinct():
        newest = eligible.filter(course_id=course_id).order_by(
            '-draft__updated_at',
            '-updated_at',
            '-id',
        ).first()
        eligible.filter(course_id=course_id).exclude(pk=newest.pk).update(
            workflow_status='abandoned',
        )


class Migration(migrations.Migration):

    dependencies = [
        ('datapipeline', '0048_question_set_wizard'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionset',
            name='workflow_status',
            field=models.CharField(
                choices=[
                    ('active', 'Active'),
                    ('completed', 'Completed'),
                    ('abandoned', 'Abandoned'),
                ],
                default='active',
                max_length=16,
            ),
        ),
        migrations.AddIndex(
            model_name='questionset',
            index=models.Index(
                fields=['course', 'workflow_status', '-updated_at'],
                name='leai_qset_course_workflow',
            ),
        ),
        migrations.RunPython(
            normalize_question_set_workflows,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='instructorauditevent',
            name='action',
            field=models.CharField(
                choices=[
                    ('auth.login_succeeded', 'Login succeeded'),
                    ('auth.login_denied', 'Login denied'),
                    ('auth.logout', 'Logout'),
                    ('account.password_changed', 'Password changed'),
                    ('account.profile_updated', 'Profile updated'),
                    ('course.created', 'Course created'),
                    ('course.banner_updated', 'Course banner updated'),
                    ('course.customization_updated', 'Course customization updated'),
                    ('survey.created', 'Survey created'),
                    ('survey.updated', 'Survey updated'),
                    ('survey.status_changed', 'Survey status changed'),
                    ('survey.cloned', 'Survey cloned'),
                    ('survey.deleted', 'Survey deleted'),
                    ('survey.responses_exported', 'Survey responses exported'),
                    ('analysis.session_created', 'Analysis session created'),
                    ('analysis.session_updated', 'Analysis session updated'),
                    ('analysis.session_deleted', 'Analysis session deleted'),
                    ('analysis.turn_started', 'Analysis turn started'),
                    ('analysis.quicktake_generated', 'Analysis quick take generated'),
                    ('analysis.quicktake_deleted', 'Analysis quick take deleted'),
                    ('team_configuration.created', 'Team configuration created'),
                    ('team_configuration.updated', 'Team configuration updated'),
                    ('team_configuration.archived', 'Team configuration archived'),
                    ('team_configuration.deleted', 'Team configuration deleted'),
                    ('pdf_ingest.started', 'PDF ingest started'),
                    ('pdf_ingest.abandoned', 'PDF ingest abandoned'),
                    ('pdf_ingest.committed', 'PDF ingest committed'),
                    ('pdf_ingest.reverted', 'PDF ingest reverted'),
                    ('question_set.draft_created', 'Question set draft created'),
                    ('question_set.draft_saved', 'Question set draft saved'),
                    ('question_set.revision_frozen', 'Question set revision frozen'),
                    ('question_set.preview_started', 'Question set preview started'),
                    ('question_set.preview_completed', 'Question set preview completed'),
                    ('question_set.workflow_abandoned', 'Question set workflow abandoned'),
                    ('question_set.workflow_completed', 'Question set workflow completed'),
                    ('authorization.denied', 'Authorization denied'),
                ],
                max_length=64,
            ),
        ),
    ]
