# Generated by Django 4.2.7 on 2026-09-13

from django.db import migrations, models
from django.db.models import F


def mark_existing_previews_ready(apps, schema_editor):
    PreviewSession = apps.get_model('datapipeline', 'PreviewSession')
    PreviewSession.objects.filter(ready_at__isnull=True).update(
        ready_at=F('created_at'),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('datapipeline', '0049_question_set_workflow_lifecycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='previewsession',
            name='ready_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.RunPython(
            mark_existing_previews_ready,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='previewsession',
            name='ready_at',
            field=models.DateTimeField(),
        ),
    ]
