# Generated by Django 4.2.7 on 2026-09-14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datapipeline', '0050_preview_session_ready_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='previewsession',
            name='completion_certificate_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='previewsession',
            name='parsed_document_download_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questionsetsurvey',
            name='completion_certificate_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='questionsetsurvey',
            name='parsed_document_download_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questionsetsurvey',
            name='preview_session',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='survey_links',
                to='datapipeline.previewsession',
            ),
        ),
        migrations.AlterField(
            model_name='instructorauditevent',
            name='action',
            field=models.CharField(
                choices=[
                    ('auth.login_succeeded', 'Login succeeded'),
                    ('auth.login_denied', 'Login denied'),
                    ('auth.logout', 'Logout'),
                    ('account.password_changed', 'Password changed'),
                    ('account.profile_updated', 'Profile updated'),
                    ('course.created', 'Course created'),
                    ('course.banner_updated', 'Course banner updated'),
                    ('course.customization_updated', 'Course customization updated'),
                    ('survey.created', 'Survey created'),
                    ('survey.updated', 'Survey updated'),
                    ('survey.status_changed', 'Survey status changed'),
                    ('survey.cloned', 'Survey cloned'),
                    ('survey.deleted', 'Survey deleted'),
                    ('survey.responses_exported', 'Survey responses exported'),
                    ('analysis.session_created', 'Analysis session created'),
                    ('analysis.session_updated', 'Analysis session updated'),
                    ('analysis.session_deleted', 'Analysis session deleted'),
                    ('analysis.turn_started', 'Analysis turn started'),
                    ('analysis.quicktake_generated', 'Analysis quick take generated'),
                    ('analysis.quicktake_deleted', 'Analysis quick take deleted'),
                    ('team_configuration.created', 'Team configuration created'),
                    ('team_configuration.updated', 'Team configuration updated'),
                    ('team_configuration.archived', 'Team configuration archived'),
                    ('team_configuration.deleted', 'Team configuration deleted'),
                    ('pdf_ingest.started', 'PDF ingest started'),
                    ('pdf_ingest.abandoned', 'PDF ingest abandoned'),
                    ('pdf_ingest.committed', 'PDF ingest committed'),
                    ('pdf_ingest.reverted', 'PDF ingest reverted'),
                    ('question_set.draft_created', 'Question set draft created'),
                    ('question_set.draft_saved', 'Question set draft saved'),
                    ('question_set.revision_frozen', 'Question set revision frozen'),
                    ('question_set.preview_started', 'Question set preview started'),
                    ('question_set.preview_completed', 'Question set preview completed'),
                    ('question_set.preview_settings_updated', 'Question set preview settings updated'),
                    ('question_set.workflow_abandoned', 'Question set workflow abandoned'),
                    ('question_set.workflow_completed', 'Question set workflow completed'),
                    ('authorization.denied', 'Authorization denied'),
                ],
                max_length=64,
            ),
        ),
    ]
