# Generated by Django 4.2.7 on 2026-09-16 22:34

from django.db import migrations, models
import django.db.models.deletion
import hashlib
import json
import uuid


def _canonical_hash(body):
    payload = json.dumps(
        body,
        sort_keys=True,
        separators=(',', ':'),
        ensure_ascii=False,
    )
    return hashlib.sha256(payload.encode('utf-8')).hexdigest()


def _legacy_body(title, intro, questions, closing):
    return {
        'schema_version': 'question-set-v1',
        'title': title,
        'intro': intro,
        'sections': [
            {
                'id': question_id,
                'title': label,
                'opening_prompt': prompt,
                'depth_probe': follow_up,
            }
            for question_id, label, prompt, follow_up in questions
        ],
        'closing': {'feedback_prompt': closing},
    }


MAGY_WEEKLY_BODY = {
    'schema_version': 'guided-feedback-v2',
    'title': 'Weekly Reflection',
    'intro': 'A guided conversation about this week\'s learning.',
    'sections': [
        {
            'id': section_id,
            'title': title,
            'questions': [{
                'id': question_id,
                'short_label': title,
                'prompt': prompt,
                'follow_up': {'enabled': True, 'prompt': follow_up},
                'response_kind': 'long_text',
            }],
        }
        for section_id, question_id, title, prompt, follow_up in (
            ('10000000-0000-4000-8000-000000000001', '20000000-0000-4000-8000-000000000001', 'Key Concepts & Takeaways', 'What is one idea or skill from this week that stayed with you, and why?', 'What specific moment helped it click?'),
            ('10000000-0000-4000-8000-000000000002', '20000000-0000-4000-8000-000000000002', 'Methods in Practice', 'Which method did you use this week? Describe one concrete moment when you used it and what happened.', 'What would you change the next time you use it?'),
            ('10000000-0000-4000-8000-000000000003', '20000000-0000-4000-8000-000000000003', 'Knowledge Shift', 'How did your understanding change this week? What did you think before, and what do you think now?', 'What challenged your earlier assumption?'),
            ('10000000-0000-4000-8000-000000000004', '20000000-0000-4000-8000-000000000004', 'Connection to the Project', 'How does this week\'s learning connect to your current project or practice?', 'Where could you apply that connection next?'),
            ('10000000-0000-4000-8000-000000000005', '20000000-0000-4000-8000-000000000005', 'Biggest Open Question', 'What important question is still unresolved for you?', 'What would help you investigate it?'),
            ('10000000-0000-4000-8000-000000000006', '20000000-0000-4000-8000-000000000006', 'Commitment for Next Week', 'What is one concrete step you will take before the next class?', 'How will you know you completed that step?'),
        )
    ],
    'closing': {'prompt': 'Is there anything else your instructor should understand?'},
}


TEAM_CHECKIN_BODY = {
    'schema_version': 'guided-feedback-v2',
    'title': 'Team Collaboration Check-in',
    'intro': 'A private guided conversation about collaboration inside your team.',
    'sections': [
        {
            'id': section_id,
            'title': title,
            'questions': [{
                'id': question_id,
                'short_label': title,
                'prompt': prompt,
                'follow_up': {'enabled': bool(follow_up), 'prompt': follow_up},
                'response_kind': 'long_text',
            }],
        }
        for section_id, question_id, title, prompt, follow_up in (
            ('30000000-0000-4000-8000-000000000001', '40000000-0000-4000-8000-000000000001', 'Work Distribution', 'How was work divided inside your team for this milestone?', 'What is one concrete example of how that division affected the work?'),
            ('30000000-0000-4000-8000-000000000002', '40000000-0000-4000-8000-000000000002', 'Communication', 'How well did your team communicate while working through decisions or problems?', 'Describe one moment that shaped your answer.'),
            ('30000000-0000-4000-8000-000000000003', '40000000-0000-4000-8000-000000000003', 'Your Contribution', 'What is one specific contribution you made to your team\'s work?', ''),
            ('30000000-0000-4000-8000-000000000004', '40000000-0000-4000-8000-000000000004', 'Next Team Change', 'What is one thing your team should change before the next milestone?', 'What would make that change realistic?'),
        )
    ],
    'closing': {'prompt': 'Is there anything else your instructor should understand about your team\'s collaboration?'},
}


COMPATIBILITY_TEMPLATES = (
    (
        'weekly-reflection',
        'Legacy weekly reflection',
        _legacy_body(
            'Weekly learning reflection',
            'A short guided conversation about this week’s learning experience.',
            (
                ('q1', 'What stood out', 'What idea, activity, or moment stood out most to you this week, and why?', 'Can you point to a specific moment that made it stand out?'),
                ('q2', 'What was difficult', 'What felt confusing, difficult, or slower than you expected this week?', 'What would have helped you make progress sooner?'),
                ('q3', 'Learning support', 'What did the instructor, course materials, or your classmates do that helped your learning?', 'Which part of that support should continue next week?'),
                ('q4', 'Next step', 'What is one concrete step you will take before the next class?', 'How will you know you completed that step?'),
            ),
            'Before you finish, what is one change that could improve next week’s learning experience?',
        ),
    ),
    (
        'mid-course-check-in',
        'Legacy mid-course check-in',
        _legacy_body(
            'Mid-course learning check-in',
            'A guided conversation to understand how the course is working so far.',
            (
                ('q1', 'Current confidence', 'How confident do you feel about the main ideas and skills covered so far?', 'What evidence from your recent work shaped that answer?'),
                ('q2', 'Course pace', 'How is the pace of the course working for you right now?', 'Where would slowing down or moving faster help most?'),
                ('q3', 'Helpful support', 'Which course activity or resource has helped your learning most so far?', 'What about it made it useful?'),
                ('q4', 'Priority for the rest of the course', 'What should the instructor prioritize during the rest of the course?', 'What difference would that change make for your learning?'),
            ),
            'Is there anything else the instructor should understand about your experience so far?',
        ),
    ),
    (
        'project-milestone',
        'Legacy project milestone reflection',
        _legacy_body(
            'Project milestone reflection',
            'A guided individual reflection on your project work and next decisions.',
            (
                ('q1', 'Progress', 'What meaningful progress did you make toward this milestone?', 'Which specific artifact, decision, or result best shows that progress?'),
                ('q2', 'Important decision', 'What was the most important decision you made, and what informed it?', 'What alternative did you consider?'),
                ('q3', 'Obstacle', 'What obstacle or uncertainty affected your work most?', 'What support or information would help you address it?'),
                ('q4', 'Next milestone', 'What is your most important next action before the next milestone?', 'What observable result will show that action is complete?'),
            ),
            'What is one thing your instructor should know when reviewing your progress?',
        ),
    ),
)


def seed_feedback_builder_templates(apps, schema_editor):
    QuestionSet = apps.get_model('datapipeline', 'QuestionSet')
    Template = apps.get_model('datapipeline', 'QuestionSetTemplate')
    Revision = apps.get_model('datapipeline', 'QuestionSetTemplateRevision')

    weekly = Template.objects.create(
        name='Weekly Reflection',
        description='Six areas for weekly learning, practice, questions, and next steps.',
        scope='global',
        audience='individual',
        collection_style='guided',
        visibility='community',
        is_active=True,
    )
    weekly_revision = Revision.objects.create(
        template=weekly,
        revision_number=1,
        canonical_body=MAGY_WEEKLY_BODY,
        content_hash=_canonical_hash(MAGY_WEEKLY_BODY),
        protocol_schema_version='guided-feedback-v2',
        provenance='seed',
    )
    weekly.community_revision_id = weekly_revision.id
    weekly.origin_revision_id = weekly_revision.id
    weekly.save(update_fields=['community_revision', 'origin_revision', 'updated_at'])

    team = Template.objects.create(
        name='Team Collaboration Check-in',
        description='Work distribution, communication, contribution, and one next change.',
        scope='global',
        audience='team',
        collection_style='guided',
        visibility='community',
        is_active=True,
    )
    team_revision = Revision.objects.create(
        template=team,
        revision_number=1,
        canonical_body=TEAM_CHECKIN_BODY,
        content_hash=_canonical_hash(TEAM_CHECKIN_BODY),
        protocol_schema_version='guided-feedback-v2',
        provenance='seed',
    )
    team.community_revision_id = team_revision.id
    team.origin_revision_id = team_revision.id
    team.save(update_fields=['community_revision', 'origin_revision', 'updated_at'])

    for legacy_id, name, body in COMPATIBILITY_TEMPLATES:
        template = Template.objects.create(
            name=name,
            description='Hidden compatibility source for the first-release Wizard.',
            scope='global',
            audience='individual',
            collection_style='guided',
            visibility='private',
            is_active=False,
        )
        revision = Revision.objects.create(
            template=template,
            revision_number=1,
            canonical_body=body,
            content_hash=_canonical_hash(body),
            protocol_schema_version='question-set-v1',
            provenance='seed',
        )
        template.origin_revision_id = revision.id
        template.save(update_fields=['origin_revision', 'updated_at'])
        QuestionSet.objects.filter(template_id=legacy_id).update(
            source_kind='template',
            source_template_revision_id=revision.id,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('datapipeline', '0052_preview_skip'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionSetDraftVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('version_number', models.PositiveIntegerField()),
                ('canonical_body', models.JSONField()),
                ('content_hash', models.CharField(max_length=64)),
                ('author_kind', models.CharField(choices=[('instructor', 'Instructor'), ('ai', 'AI'), ('system', 'System'), ('restore', 'Restore')], max_length=16)),
                ('change_set', models.JSONField(default=list)),
                ('summary', models.CharField(blank=True, default='', max_length=240)),
                ('rationale', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['question_set_id', 'version_number'],
            },
        ),
        migrations.CreateModel(
            name='QuestionSetTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('scope', models.CharField(choices=[('global', 'Global'), ('instructor', 'Instructor'), ('institution', 'Institution')], max_length=16)),
                ('audience', models.CharField(choices=[('individual', 'Individual feedback'), ('team', 'Team feedback')], max_length=20)),
                ('collection_style', models.CharField(choices=[('guided', 'Guided feedback'), ('open', 'Open conversation')], max_length=16)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('community', 'Community')], default='private', max_length=16)),
                ('community_published_at', models.DateTimeField(blank=True, null=True)),
                ('community_withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuestionSetTemplateRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('revision_number', models.PositiveIntegerField()),
                ('canonical_body', models.JSONField()),
                ('content_hash', models.CharField(max_length=64)),
                ('protocol_schema_version', models.CharField(max_length=32)),
                ('provenance', models.CharField(choices=[('seed', 'Seed'), ('instructor_saved', 'Instructor saved'), ('imported', 'Imported')], max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['template_id', 'revision_number'],
            },
        ),
        migrations.AddField(
            model_name='questionset',
            name='aggregation_scope',
            field=models.CharField(choices=[('course', 'Course'), ('team', 'Team')], default='course', max_length=16),
        ),
        migrations.AddField(
            model_name='questionset',
            name='collection_style',
            field=models.CharField(choices=[('guided', 'Guided feedback'), ('open', 'Open conversation')], default='guided', max_length=16),
        ),
        migrations.AddField(
            model_name='questionset',
            name='response_unit',
            field=models.CharField(choices=[('individual', 'Individual response')], default='individual', max_length=16),
        ),
        migrations.AddField(
            model_name='questionset',
            name='source_kind',
            field=models.CharField(choices=[('template', 'Template'), ('blank', 'Blank'), ('copied_revision', 'Copied revision'), ('legacy', 'Legacy')], default='legacy', max_length=24),
        ),
        migrations.AddField(
            model_name='questionset',
            name='source_question_set_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='copied_question_sets', to='datapipeline.questionsetrevision'),
        ),
        migrations.AddField(
            model_name='questionsetrevision',
            name='author_kind',
            field=models.CharField(choices=[('instructor', 'Instructor'), ('ai', 'AI'), ('system', 'System'), ('restore', 'Restore')], default='instructor', max_length=16),
        ),
        migrations.AddField(
            model_name='questionsetrevision',
            name='protocol_schema_version',
            field=models.CharField(default='guided-feedback-v1', max_length=32),
        ),
        migrations.AlterField(
            model_name='questionset',
            name='audience',
            field=models.CharField(choices=[('individual', 'Individual feedback'), ('team', 'Team feedback')], default='individual', max_length=20),
        ),
        migrations.AlterField(
            model_name='questionset',
            name='template_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='questionset',
            name='source_template_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_question_sets', to='datapipeline.questionsettemplaterevision'),
        ),
        migrations.AddConstraint(
            model_name='questionset',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('aggregation_scope', 'course'), ('audience', 'individual'), ('collection_style__in', ['guided', 'open'])), models.Q(('aggregation_scope', 'team'), ('audience', 'team'), ('collection_style', 'guided')), _connector='OR'), name='leai_qset_supported_taxonomy'),
        ),
        migrations.AddConstraint(
            model_name='questionset',
            constraint=models.CheckConstraint(check=models.Q(('response_unit', 'individual')), name='leai_qset_individual_response_unit'),
        ),
        migrations.AddConstraint(
            model_name='questionset',
            constraint=models.UniqueConstraint(condition=models.Q(('workflow_status', 'active'), ('archived_at__isnull', True)), fields=('course',), name='leai_one_active_qset_per_course'),
        ),
        migrations.AddField(
            model_name='questionsettemplaterevision',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_question_set_template_revisions', to='datapipeline.instructoraccount'),
        ),
        migrations.AddField(
            model_name='questionsettemplaterevision',
            name='source_checkpoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='saved_template_revisions', to='datapipeline.questionsetdraftversion'),
        ),
        migrations.AddField(
            model_name='questionsettemplaterevision',
            name='source_question_set_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='saved_template_revisions', to='datapipeline.questionsetrevision'),
        ),
        migrations.AddField(
            model_name='questionsettemplaterevision',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='datapipeline.questionsettemplate'),
        ),
        migrations.AddField(
            model_name='questionsettemplate',
            name='community_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='datapipeline.questionsettemplaterevision'),
        ),
        migrations.AddField(
            model_name='questionsettemplate',
            name='forked_from_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='direct_forks', to='datapipeline.questionsettemplaterevision'),
        ),
        migrations.AddField(
            model_name='questionsettemplate',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='question_set_templates', to='datapipeline.institution'),
        ),
        migrations.AddField(
            model_name='questionsettemplate',
            name='origin_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='origin_templates', to='datapipeline.questionsettemplaterevision'),
        ),
        migrations.AddField(
            model_name='questionsettemplate',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='question_set_templates', to='datapipeline.instructoraccount'),
        ),
        migrations.AddField(
            model_name='questionsetdraftversion',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='question_set_draft_versions', to='datapipeline.instructoraccount'),
        ),
        migrations.AddField(
            model_name='questionsetdraftversion',
            name='parent_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_versions', to='datapipeline.questionsetdraftversion'),
        ),
        migrations.AddField(
            model_name='questionsetdraftversion',
            name='question_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='draft_versions', to='datapipeline.questionset'),
        ),
        migrations.AddField(
            model_name='questionsetdraftversion',
            name='restored_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='restore_versions', to='datapipeline.questionsetdraftversion'),
        ),
        migrations.AddField(
            model_name='questionsetdraftversion',
            name='source_template_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_draft_versions', to='datapipeline.questionsettemplaterevision'),
        ),
        migrations.AddField(
            model_name='questionsetdraft',
            name='current_checkpoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_for_drafts', to='datapipeline.questionsetdraftversion'),
        ),
        migrations.AddField(
            model_name='questionsetrevision',
            name='source_checkpoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='frozen_revisions', to='datapipeline.questionsetdraftversion'),
        ),
        migrations.RunPython(
            seed_feedback_builder_templates,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='questionset',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('source_kind', 'template'), ('source_question_set_revision__isnull', True), ('source_template_revision__isnull', False)), models.Q(('source_kind', 'copied_revision'), ('source_question_set_revision__isnull', False), ('source_template_revision__isnull', True)), models.Q(('source_kind__in', ['blank', 'legacy']), ('source_question_set_revision__isnull', True), ('source_template_revision__isnull', True)), _connector='OR'), name='leai_qset_source_matches_kind'),
        ),
        migrations.AddConstraint(
            model_name='questionsettemplaterevision',
            constraint=models.UniqueConstraint(fields=('template', 'revision_number'), name='leai_unique_template_revision_number'),
        ),
        migrations.AddConstraint(
            model_name='questionsettemplaterevision',
            constraint=models.UniqueConstraint(fields=('template', 'content_hash'), name='leai_unique_template_revision_hash'),
        ),
        migrations.AddConstraint(
            model_name='questionsettemplate',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('owner__isnull', True), ('scope', 'global')), models.Q(('owner__isnull', False), ('scope', 'instructor')), ('scope', 'institution'), _connector='OR'), name='leai_qset_template_scope_owner'),
        ),
        migrations.AddConstraint(
            model_name='questionsettemplate',
            constraint=models.CheckConstraint(check=models.Q(('audience', 'individual'), models.Q(('audience', 'team'), ('collection_style', 'guided')), _connector='OR'), name='leai_qset_template_supported_style'),
        ),
        migrations.AddConstraint(
            model_name='questionsetdraftversion',
            constraint=models.UniqueConstraint(fields=('question_set', 'version_number'), name='leai_unique_draft_version_number'),
        ),
    ]
