# Generated by Django 4.2.7 on 2026-09-16 22:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('datapipeline', '0053_feedback_builder_v12_foundation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthoringConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='active', max_length=16)),
                ('next_message_sequence', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authoring_conversations', to='datapipeline.course')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authoring_conversations', to='datapipeline.instructoraccount')),
                ('question_set', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='authoring_conversation', to='datapipeline.questionset')),
            ],
        ),
        migrations.CreateModel(
            name='AuthoringMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('role', models.CharField(choices=[('instructor', 'Instructor'), ('assistant', 'Assistant'), ('system', 'System')], max_length=16)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='authoring_messages', to='datapipeline.instructoraccount')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='datapipeline.authoringconversation')),
                ('resulting_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='authoring_messages', to='datapipeline.questionsetdraftversion')),
            ],
            options={
                'ordering': ['sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AuthoringRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('applied', 'Applied'), ('conflict', 'Conflict'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=24)),
                ('provider', models.CharField(default='openai', max_length=32)),
                ('model', models.CharField(blank=True, default='', max_length=100)),
                ('prompt_policy_version', models.CharField(default='v12-1', max_length=32)),
                ('requested_operations', models.JSONField(default=list)),
                ('validated_operations', models.JSONField(default=list)),
                ('change_summary', models.CharField(blank=True, default='', max_length=240)),
                ('rationale', models.TextField(blank=True, default='')),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('idempotency_key', models.CharField(max_length=100)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_version', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applied_authoring_run', to='datapipeline.questionsetdraftversion')),
                ('base_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='based_authoring_runs', to='datapipeline.questionsetdraftversion')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='datapipeline.authoringconversation')),
                ('request_message', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_runs', to='datapipeline.authoringmessage')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionSetMutationReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=100)),
                ('operation_kind', models.CharField(max_length=32)),
                ('idempotency_key', models.CharField(max_length=100)),
                ('request_hash', models.CharField(max_length=64)),
                ('result_draft_version', models.PositiveIntegerField(blank=True, null=True)),
                ('outcome', models.CharField(default='success', max_length=16)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mutation_receipts', to='datapipeline.questionsetsurvey')),
                ('result_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mutation_receipts', to='datapipeline.questionsetdraftversion')),
            ],
        ),
        migrations.CreateModel(
            name='AuthoringRunSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('template_revision', 'Template revision'), ('question_set_revision', 'Question set revision'), ('authoring_rule', 'Authoring rule')], max_length=32)),
                ('stable_identifier', models.CharField(max_length=200)),
                ('content_hash', models.CharField(max_length=64)),
                ('label', models.CharField(max_length=200)),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('relevance_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sources', to='datapipeline.authoringrun')),
            ],
        ),
        migrations.AddConstraint(
            model_name='questionsetmutationreceipt',
            constraint=models.UniqueConstraint(fields=('scope', 'idempotency_key'), name='leai_unique_mutation_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='authoringrun',
            constraint=models.UniqueConstraint(fields=('conversation', 'idempotency_key'), name='leai_unique_authoring_run_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='authoringmessage',
            constraint=models.UniqueConstraint(fields=('conversation', 'sequence'), name='leai_unique_authoring_message_sequence'),
        ),
    ]
