# Generated by Django 4.2.7 on 2026-09-16 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datapipeline', '0054_feedback_builder_authoring'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionsetsurvey',
            name='publication_manifest',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='questionsetsurvey',
            name='team_configuration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='question_set_surveys', to='datapipeline.teamconfiguration'),
        ),
    ]
