# Generated by Django 4.2.7 on 2026-09-22 02:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('course_code', models.SlugField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('lifecycle_state', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], default='active', max_length=16)),
                ('settings_version', models.PositiveIntegerField(default=1)),
                ('analysis_data_version', models.PositiveBigIntegerField(default=0)),
                ('banner_enabled', models.BooleanField(default=False)),
                ('banner_text', models.TextField(blank=True, default='')),
                ('banner_dismissible', models.BooleanField(default=False)),
                ('banner_display_mode', models.CharField(choices=[('persistent', 'Persistent'), ('timed', 'Timed')], default='persistent', max_length=16)),
                ('banner_duration_seconds', models.PositiveIntegerField(default=10)),
                ('banner_split_enabled', models.BooleanField(default=False)),
                ('banner_split_mode', models.CharField(choices=[('percentage', 'Percentage'), ('count', 'Count')], default='percentage', max_length=16)),
                ('banner_split_value', models.PositiveIntegerField(default=50)),
                ('assistant_display_name', models.CharField(blank=True, default='', max_length=100)),
                ('referral_enabled', models.BooleanField(default=False)),
                ('referral_text', models.CharField(blank=True, default='', max_length=200)),
                ('completion_certificate_enabled_by_default', models.BooleanField(default=False)),
                ('completed_response_download_enabled_by_default', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='InstructorAccount',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('platform_role', models.CharField(choices=[('member', 'Member'), ('platform_admin', 'Platform Admin')], default='member', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('must_change_password', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InstructorSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capability_digest', models.CharField(max_length=128, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='leai.instructoraccount')),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('instructor', 'Instructor'), ('researcher', 'Researcher')], max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='institution_memberships', to='leai.instructoraccount')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instructor_memberships', to='leai.institution')),
            ],
        ),
        migrations.CreateModel(
            name='CourseMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('instructor', 'Instructor'), ('ta', 'Ta')], max_length=16)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='leai.course')),
                ('institution_membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_memberships', to='leai.institutionmembership')),
            ],
        ),
        migrations.CreateModel(
            name='CourseAccessRestriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denied', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_restrictions', to='leai.course')),
                ('institution_membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_access_restrictions', to='leai.institutionmembership')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='leai.institution'),
        ),
        migrations.AddConstraint(
            model_name='institutionmembership',
            constraint=models.UniqueConstraint(fields=('account', 'institution'), name='leai_institution_membership_account_institution_uniq'),
        ),
        migrations.AddConstraint(
            model_name='coursemembership',
            constraint=models.UniqueConstraint(fields=('course', 'institution_membership'), name='leai_course_membership_course_institution_membership_uniq'),
        ),
        migrations.AddConstraint(
            model_name='courseaccessrestriction',
            constraint=models.UniqueConstraint(fields=('course', 'institution_membership'), name='leai_course_access_restriction_course_membership_uniq'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('institution', 'course_code'), name='leai_course_code_per_institution_uniq'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.CheckConstraint(check=models.Q(('banner_display_mode', 'persistent'), models.Q(('banner_display_mode', 'timed'), ('banner_duration_seconds__gt', 0)), _connector='OR'), name='leai_course_timed_banner_duration_positive'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('banner_split_mode', 'percentage'), ('banner_split_value__gte', 0), ('banner_split_value__lte', 100)), models.Q(('banner_split_mode', 'count'), ('banner_split_value__gt', 0)), _connector='OR'), name='leai_course_banner_split_value_valid'),
        ),
        migrations.RunSQL(
            sql="""
                ALTER TABLE leai_instructoraccount
                    ALTER COLUMN public_id SET DEFAULT gen_random_uuid();
                ALTER TABLE leai_course
                    ALTER COLUMN public_id SET DEFAULT gen_random_uuid();

                CREATE FUNCTION leai_reject_public_id_update()
                RETURNS TRIGGER AS $$
                BEGIN
                    IF NEW.public_id IS DISTINCT FROM OLD.public_id THEN
                        RAISE EXCEPTION USING
                            ERRCODE = '23514',
                            MESSAGE = 'LEAI public_id values are immutable';
                    END IF;
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER leai_instructoraccount_public_id_immutable
                BEFORE UPDATE OF public_id ON leai_instructoraccount
                FOR EACH ROW EXECUTE FUNCTION leai_reject_public_id_update();

                CREATE TRIGGER leai_course_public_id_immutable
                BEFORE UPDATE OF public_id ON leai_course
                FOR EACH ROW EXECUTE FUNCTION leai_reject_public_id_update();

                CREATE FUNCTION leai_enforce_course_institution_membership()
                RETURNS TRIGGER AS $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1
                        FROM leai_course AS course
                        JOIN leai_institutionmembership AS institution_membership
                          ON institution_membership.id = NEW.institution_membership_id
                        WHERE course.id = NEW.course_id
                          AND course.institution_id = institution_membership.institution_id
                    ) THEN
                        RAISE EXCEPTION USING
                            ERRCODE = '23514',
                            MESSAGE = 'Course membership institution must match course institution';
                    END IF;
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER leai_course_membership_same_institution
                BEFORE INSERT OR UPDATE ON leai_coursemembership
                FOR EACH ROW EXECUTE FUNCTION leai_enforce_course_institution_membership();

                CREATE TRIGGER leai_course_access_restriction_same_institution
                BEFORE INSERT OR UPDATE ON leai_courseaccessrestriction
                FOR EACH ROW EXECUTE FUNCTION leai_enforce_course_institution_membership();
            """,
            reverse_sql="""
                DROP TRIGGER IF EXISTS leai_course_access_restriction_same_institution
                    ON leai_courseaccessrestriction;
                DROP TRIGGER IF EXISTS leai_course_membership_same_institution
                    ON leai_coursemembership;
                DROP FUNCTION IF EXISTS leai_enforce_course_institution_membership();

                DROP TRIGGER IF EXISTS leai_course_public_id_immutable ON leai_course;
                DROP TRIGGER IF EXISTS leai_instructoraccount_public_id_immutable
                    ON leai_instructoraccount;
                DROP FUNCTION IF EXISTS leai_reject_public_id_update();

                ALTER TABLE leai_course ALTER COLUMN public_id DROP DEFAULT;
                ALTER TABLE leai_instructoraccount ALTER COLUMN public_id DROP DEFAULT;
            """,
        ),
    ]
