# Generated by Django 4.2.7 on 2026-09-22 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leai', '0001_identity_course'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='course',
            constraint=models.CheckConstraint(check=models.Q(('lifecycle_state__in', ['active', 'completed', 'archived'])), name='leai_course_lifecycle_state_valid'),
        ),
        migrations.AddConstraint(
            model_name='coursemembership',
            constraint=models.CheckConstraint(check=models.Q(('role__in', ['owner', 'instructor', 'ta'])), name='leai_course_membership_role_valid'),
        ),
        migrations.AddConstraint(
            model_name='institutionmembership',
            constraint=models.CheckConstraint(check=models.Q(('role__in', ['instructor', 'researcher'])), name='leai_institution_membership_role_valid'),
        ),
        migrations.AddConstraint(
            model_name='instructoraccount',
            constraint=models.CheckConstraint(check=models.Q(('platform_role__in', ['member', 'platform_admin'])), name='leai_instructor_account_platform_role_valid'),
        ),
        migrations.RunSQL(
            sql="""
                CREATE FUNCTION leai_enforce_parent_institution_update()
                RETURNS TRIGGER AS $$
                BEGIN
                    IF TG_TABLE_NAME = 'leai_course' THEN
                        IF EXISTS (
                            SELECT 1
                            FROM leai_coursemembership AS course_membership
                            JOIN leai_institutionmembership AS institution_membership
                              ON institution_membership.id = course_membership.institution_membership_id
                            WHERE course_membership.course_id = NEW.id
                              AND institution_membership.institution_id <> NEW.institution_id
                        ) OR EXISTS (
                            SELECT 1
                            FROM leai_courseaccessrestriction AS restriction
                            JOIN leai_institutionmembership AS institution_membership
                              ON institution_membership.id = restriction.institution_membership_id
                            WHERE restriction.course_id = NEW.id
                              AND institution_membership.institution_id <> NEW.institution_id
                        ) THEN
                            RAISE EXCEPTION USING
                                ERRCODE = '23514',
                                MESSAGE = 'Course institution must match dependent membership institutions';
                        END IF;
                    ELSIF TG_TABLE_NAME = 'leai_institutionmembership' THEN
                        IF EXISTS (
                            SELECT 1
                            FROM leai_coursemembership AS course_membership
                            JOIN leai_course AS course ON course.id = course_membership.course_id
                            WHERE course_membership.institution_membership_id = NEW.id
                              AND course.institution_id <> NEW.institution_id
                        ) OR EXISTS (
                            SELECT 1
                            FROM leai_courseaccessrestriction AS restriction
                            JOIN leai_course AS course ON course.id = restriction.course_id
                            WHERE restriction.institution_membership_id = NEW.id
                              AND course.institution_id <> NEW.institution_id
                        ) THEN
                            RAISE EXCEPTION USING
                                ERRCODE = '23514',
                                MESSAGE = 'Institution membership institution must match dependent courses';
                        END IF;
                    END IF;
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER leai_course_parent_institution_consistent
                BEFORE UPDATE OF institution_id ON leai_course
                FOR EACH ROW EXECUTE FUNCTION leai_enforce_parent_institution_update();

                CREATE TRIGGER leai_institution_membership_parent_institution_consistent
                BEFORE UPDATE OF institution_id ON leai_institutionmembership
                FOR EACH ROW EXECUTE FUNCTION leai_enforce_parent_institution_update();
            """,
            reverse_sql="""
                DROP TRIGGER IF EXISTS leai_institution_membership_parent_institution_consistent
                    ON leai_institutionmembership;
                DROP TRIGGER IF EXISTS leai_course_parent_institution_consistent ON leai_course;
                DROP FUNCTION IF EXISTS leai_enforce_parent_institution_update();
            """,
        ),
    ]
