# Generated by Django 4.2.7 on 2026-09-22 03:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('leai', '0003_lock_child_institution_parents'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionSet',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('audience', models.CharField(choices=[('individual', 'Individual'), ('team', 'Team')], default='individual', max_length=16)),
                ('collection_style', models.CharField(choices=[('guided', 'Guided'), ('open', 'Open')], default='guided', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_sets', to='leai.course')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_question_sets', to='leai.instructoraccount')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionSetDraft',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('current_version', models.PositiveIntegerField(default=1)),
                ('canonical_body', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionSetDraftVersion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('content_hash', models.CharField(max_length=64)),
                ('canonical_body', models.JSONField(default=dict)),
                ('change_kind', models.CharField(choices=[('manual', 'Manual'), ('ai', 'AI'), ('restore', 'Restore'), ('delete', 'Delete')], default='manual', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_question_set_draft_versions', to='leai.instructoraccount')),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='leai.questionsetdraft')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionSetRevision',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('revision_number', models.PositiveIntegerField()),
                ('content_hash', models.CharField(max_length=64)),
                ('compiled_protocol', models.JSONField(default=dict)),
                ('compiler_version', models.CharField(max_length=64)),
                ('engine_version', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_question_set_revisions', to='leai.instructoraccount')),
                ('question_set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='leai.questionset')),
                ('source_draft_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compiled_revisions', to='leai.questionsetdraftversion')),
            ],
        ),
        migrations.AddField(
            model_name='questionsetdraft',
            name='base_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='based_drafts', to='leai.questionsetrevision'),
        ),
        migrations.AddField(
            model_name='questionsetdraft',
            name='question_set',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='draft', to='leai.questionset'),
        ),
        migrations.AddField(
            model_name='questionsetdraft',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_question_set_drafts', to='leai.instructoraccount'),
        ),
        migrations.AddField(
            model_name='questionset',
            name='source_question_set_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sourced_question_sets', to='leai.questionsetrevision'),
        ),
        migrations.AddConstraint(
            model_name='questionsetrevision',
            constraint=models.UniqueConstraint(fields=('question_set', 'revision_number'), name='leai_question_set_revision_number_uniq'),
        ),
        migrations.AddConstraint(
            model_name='questionsetrevision',
            constraint=models.CheckConstraint(check=models.Q(('content_hash__regex', '^[0-9a-f]{64}$')), name='leai_question_set_revision_hash_valid'),
        ),
        migrations.AddConstraint(
            model_name='questionsetdraftversion',
            constraint=models.UniqueConstraint(fields=('draft', 'version_number'), name='leai_question_set_draft_version_number_uniq'),
        ),
        migrations.AddConstraint(
            model_name='questionsetdraftversion',
            constraint=models.CheckConstraint(check=models.Q(('change_kind__in', ['manual', 'ai', 'restore', 'delete'])), name='leai_question_set_draft_version_change_kind_valid'),
        ),
        migrations.AddConstraint(
            model_name='questionsetdraftversion',
            constraint=models.CheckConstraint(check=models.Q(('content_hash__regex', '^[0-9a-f]{64}$')), name='leai_question_set_draft_version_hash_valid'),
        ),
        migrations.AddConstraint(
            model_name='questionsetdraft',
            constraint=models.CheckConstraint(check=models.Q(('current_version__gte', 1)), name='leai_question_set_draft_current_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='questionset',
            constraint=models.CheckConstraint(check=models.Q(('audience__in', ['individual', 'team'])), name='leai_question_set_audience_valid'),
        ),
        migrations.AddConstraint(
            model_name='questionset',
            constraint=models.CheckConstraint(check=models.Q(('collection_style__in', ['guided', 'open'])), name='leai_question_set_collection_style_valid'),
        ),
        migrations.AddConstraint(
            model_name='questionset',
            constraint=models.CheckConstraint(check=models.Q(('audience', 'team'), ('collection_style', 'open'), _negated=True), name='leai_question_set_team_open_rejected'),
        ),
        migrations.RunSQL(
            sql="""
                ALTER TABLE leai_questionset
                    ALTER COLUMN public_id SET DEFAULT gen_random_uuid();
                ALTER TABLE leai_questionsetrevision
                    ALTER COLUMN public_id SET DEFAULT gen_random_uuid();

                CREATE FUNCTION leai_reject_authoring_public_id_update()
                RETURNS TRIGGER AS $$
                BEGIN
                    IF NEW.public_id IS DISTINCT FROM OLD.public_id THEN
                        RAISE EXCEPTION USING
                            ERRCODE = '23514',
                            MESSAGE = 'LEAI authoring public_id values are immutable';
                    END IF;
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER leai_questionset_public_id_immutable
                BEFORE UPDATE OF public_id ON leai_questionset
                FOR EACH ROW EXECUTE FUNCTION leai_reject_authoring_public_id_update();

                CREATE TRIGGER leai_questionsetrevision_public_id_immutable
                BEFORE UPDATE OF public_id ON leai_questionsetrevision
                FOR EACH ROW EXECUTE FUNCTION leai_reject_authoring_public_id_update();

                CREATE FUNCTION leai_reject_question_set_identity_update()
                RETURNS TRIGGER AS $$
                BEGIN
                    IF NEW.course_id IS DISTINCT FROM OLD.course_id
                       OR NEW.owner_id IS DISTINCT FROM OLD.owner_id
                       OR NEW.source_question_set_revision_id
                          IS DISTINCT FROM OLD.source_question_set_revision_id THEN
                        RAISE EXCEPTION USING
                            ERRCODE = '23514',
                            MESSAGE = 'Question Set course, owner, and source revision are immutable';
                    END IF;
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER leai_questionset_identity_immutable
                BEFORE UPDATE OF course_id, owner_id, source_question_set_revision_id
                ON leai_questionset
                FOR EACH ROW EXECUTE FUNCTION leai_reject_question_set_identity_update();

                CREATE FUNCTION leai_reject_draft_question_set_update()
                RETURNS TRIGGER AS $$
                BEGIN
                    IF NEW.question_set_id IS DISTINCT FROM OLD.question_set_id THEN
                        RAISE EXCEPTION USING
                            ERRCODE = '23514',
                            MESSAGE = 'Question Set Draft question_set is immutable';
                    END IF;
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER leai_questionsetdraft_question_set_immutable
                BEFORE UPDATE OF question_set_id ON leai_questionsetdraft
                FOR EACH ROW EXECUTE FUNCTION leai_reject_draft_question_set_update();

                CREATE FUNCTION leai_reject_immutable_authoring_history()
                RETURNS TRIGGER AS $$
                BEGIN
                    RAISE EXCEPTION USING
                        ERRCODE = '23514',
                        MESSAGE = 'Question Set draft versions and revisions are immutable';
                END;
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER leai_questionsetdraftversion_immutable
                BEFORE UPDATE OR DELETE ON leai_questionsetdraftversion
                FOR EACH ROW EXECUTE FUNCTION leai_reject_immutable_authoring_history();

                CREATE TRIGGER leai_questionsetrevision_immutable
                BEFORE UPDATE OR DELETE ON leai_questionsetrevision
                FOR EACH ROW EXECUTE FUNCTION leai_reject_immutable_authoring_history();

                CREATE FUNCTION leai_enforce_question_set_source_revision()
                RETURNS TRIGGER AS $$
                DECLARE
                    source_course_id bigint;
                BEGIN
                    IF NEW.source_question_set_revision_id IS NULL THEN
                        RETURN NEW;
                    END IF;

                    PERFORM 1
                    FROM leai_course
                    WHERE id = NEW.course_id
                    FOR UPDATE;

                    SELECT source_question_set.course_id
                    INTO source_course_id
                    FROM leai_questionsetrevision AS source_revision
                    JOIN leai_questionset AS source_question_set
                      ON source_question_set.id = source_revision.question_set_id
                    WHERE source_revision.id = NEW.source_question_set_revision_id
                    FOR UPDATE OF source_revision, source_question_set;

                    IF source_course_id IS NULL OR source_course_id <> NEW.course_id THEN
                        RAISE EXCEPTION USING
                            ERRCODE = '23514',
                            MESSAGE = 'Question Set source revision must belong to the same Course';
                    END IF;
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER leai_questionset_source_revision_same_course
                BEFORE INSERT OR UPDATE OF source_question_set_revision_id
                ON leai_questionset
                FOR EACH ROW EXECUTE FUNCTION leai_enforce_question_set_source_revision();

                CREATE FUNCTION leai_enforce_draft_base_revision()
                RETURNS TRIGGER AS $$
                DECLARE
                    base_question_set_id bigint;
                BEGIN
                    IF NEW.base_revision_id IS NULL THEN
                        RETURN NEW;
                    END IF;

                    SELECT question_set_id
                    INTO base_question_set_id
                    FROM leai_questionsetrevision
                    WHERE id = NEW.base_revision_id
                    FOR UPDATE;

                    PERFORM 1
                    FROM leai_questionset
                    WHERE id IN (NEW.question_set_id, base_question_set_id)
                    ORDER BY id
                    FOR UPDATE;

                    IF base_question_set_id IS NULL
                       OR base_question_set_id <> NEW.question_set_id THEN
                        RAISE EXCEPTION USING
                            ERRCODE = '23514',
                            MESSAGE = 'Question Set Draft base revision must belong to its Question Set';
                    END IF;
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER leai_questionsetdraft_base_revision_same_question_set
                BEFORE INSERT OR UPDATE OF base_revision_id
                ON leai_questionsetdraft
                FOR EACH ROW EXECUTE FUNCTION leai_enforce_draft_base_revision();

                CREATE FUNCTION leai_enforce_revision_source_draft_version()
                RETURNS TRIGGER AS $$
                DECLARE
                    source_question_set_id bigint;
                BEGIN
                    SELECT draft.question_set_id
                    INTO source_question_set_id
                    FROM leai_questionsetdraftversion AS source_version
                    JOIN leai_questionsetdraft AS draft ON draft.id = source_version.draft_id
                    WHERE source_version.id = NEW.source_draft_version_id
                    FOR UPDATE OF source_version, draft;

                    PERFORM 1
                    FROM leai_questionset
                    WHERE id IN (NEW.question_set_id, source_question_set_id)
                    ORDER BY id
                    FOR UPDATE;

                    IF source_question_set_id IS NULL
                       OR source_question_set_id <> NEW.question_set_id THEN
                        RAISE EXCEPTION USING
                            ERRCODE = '23514',
                            MESSAGE = 'Question Set Revision source draft version must belong to its Question Set';
                    END IF;
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER leai_questionsetrevision_source_draft_version_same_question_set
                BEFORE INSERT OR UPDATE OF source_draft_version_id
                ON leai_questionsetrevision
                FOR EACH ROW EXECUTE FUNCTION leai_enforce_revision_source_draft_version();
            """,
            reverse_sql="""
                DROP TRIGGER IF EXISTS leai_questionsetrevision_source_draft_version_same_question_set
                    ON leai_questionsetrevision;
                DROP FUNCTION IF EXISTS leai_enforce_revision_source_draft_version();

                DROP TRIGGER IF EXISTS leai_questionsetdraft_base_revision_same_question_set
                    ON leai_questionsetdraft;
                DROP FUNCTION IF EXISTS leai_enforce_draft_base_revision();

                DROP TRIGGER IF EXISTS leai_questionset_source_revision_same_course
                    ON leai_questionset;
                DROP FUNCTION IF EXISTS leai_enforce_question_set_source_revision();

                DROP TRIGGER IF EXISTS leai_questionsetrevision_immutable
                    ON leai_questionsetrevision;
                DROP TRIGGER IF EXISTS leai_questionsetdraftversion_immutable
                    ON leai_questionsetdraftversion;
                DROP FUNCTION IF EXISTS leai_reject_immutable_authoring_history();

                DROP TRIGGER IF EXISTS leai_questionsetdraft_question_set_immutable
                    ON leai_questionsetdraft;
                DROP FUNCTION IF EXISTS leai_reject_draft_question_set_update();

                DROP TRIGGER IF EXISTS leai_questionset_identity_immutable ON leai_questionset;
                DROP FUNCTION IF EXISTS leai_reject_question_set_identity_update();

                DROP TRIGGER IF EXISTS leai_questionsetrevision_public_id_immutable
                    ON leai_questionsetrevision;
                DROP TRIGGER IF EXISTS leai_questionset_public_id_immutable ON leai_questionset;
                DROP FUNCTION IF EXISTS leai_reject_authoring_public_id_update();

                ALTER TABLE leai_questionsetrevision ALTER COLUMN public_id DROP DEFAULT;
                ALTER TABLE leai_questionset ALTER COLUMN public_id DROP DEFAULT;
            """,
        ),
    ]
