# Generated by Django 4.2.7 on 2026-09-22 17:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('leai', '0004_authoring_core'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthoringConversation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('origin_surface', models.CharField(choices=[('builder', 'Builder'), ('instructor_insights', 'Instructor Insights'), ('survey_list', 'Survey List'), ('template', 'Template')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_authoring_conversations', to='leai.instructoraccount')),
                ('question_set', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='authoring_conversation', to='leai.questionset')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionSetTemplate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_question_set_templates', to='leai.instructoraccount')),
                ('owner_institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_question_set_templates', to='leai.institution')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyOccurrence',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('label', models.CharField(max_length=200)),
                ('provenance', models.CharField(choices=[('native', 'Native'), ('imported', 'Imported')], default='native', max_length=16)),
                ('management_mode', models.CharField(choices=[('managed', 'Managed'), ('imported_read_only', 'Imported read only')], default='managed', max_length=32)),
                ('opens_at', models.DateTimeField(blank=True, null=True)),
                ('closes_at', models.DateTimeField(blank=True, null=True)),
                ('manually_closed_at', models.DateTimeField(blank=True, null=True)),
                ('settings_version', models.PositiveIntegerField(default=1)),
                ('completion_certificate_enabled', models.BooleanField(default=False)),
                ('completed_response_download_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='survey_occurrences', to='leai.course')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_survey_occurrences', to='leai.instructoraccount')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='survey_occurrences', to='leai.questionsetrevision')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionSetTemplateRevision',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('revision_number', models.PositiveIntegerField()),
                ('content_hash', models.CharField(max_length=64)),
                ('canonical_body', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_question_set_template_revisions', to='leai.instructoraccount')),
                ('source_question_set_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sourced_template_revisions', to='leai.questionsetrevision')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='leai.questionsettemplate')),
            ],
        ),
        migrations.CreateModel(
            name='PreviewSession',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('capability_digest', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preview_sessions', to='leai.instructoraccount')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preview_sessions', to='leai.questionsetrevision')),
            ],
        ),
        migrations.CreateModel(
            name='PreviewMessage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField()),
                ('role', models.CharField(choices=[('student', 'Student'), ('assistant', 'Assistant'), ('system', 'System')], max_length=16)),
                ('content', models.TextField()),
                ('attribution', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('preview_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='leai.previewsession')),
            ],
        ),
        migrations.CreateModel(
            name='PreviewDecision',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('decision', models.CharField(choices=[('completed', 'Completed'), ('skipped', 'Skipped')], max_length=16)),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('idempotency_key_hash', models.CharField(max_length=64, unique=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preview_decisions', to='leai.instructoraccount')),
                ('revision', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='preview_decision', to='leai.questionsetrevision')),
            ],
        ),
        migrations.CreateModel(
            name='AuthoringRun',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='pending', max_length=16)),
                ('source_provenance_snapshot', models.JSONField()),
                ('bounded_result', models.JSONField(blank=True, null=True)),
                ('bounded_error_code', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('base_draft_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authoring_runs', to='leai.questionsetdraftversion')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='leai.authoringconversation')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_authoring_runs', to='leai.instructoraccount')),
            ],
        ),
        migrations.CreateModel(
            name='AuthoringMessage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField()),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=16)),
                ('input_method', models.CharField(blank=True, choices=[('typed', 'Typed'), ('voice', 'Voice')], max_length=16, null=True)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='leai.authoringconversation')),
            ],
        ),
        migrations.AddConstraint(
            model_name='surveyoccurrence',
            constraint=models.CheckConstraint(check=models.Q(('provenance__in', ['native', 'imported'])), name='leai_survey_occurrence_provenance_valid'),
        ),
        migrations.AddConstraint(
            model_name='surveyoccurrence',
            constraint=models.CheckConstraint(check=models.Q(('management_mode__in', ['managed', 'imported_read_only'])), name='leai_survey_occurrence_management_mode_valid'),
        ),
        migrations.AddConstraint(
            model_name='surveyoccurrence',
            constraint=models.CheckConstraint(check=models.Q(('settings_version__gte', 1)), name='leai_survey_occurrence_settings_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='surveyoccurrence',
            constraint=models.CheckConstraint(check=models.Q(('opens_at__isnull', True), ('closes_at__isnull', True), ('opens_at__lte', models.F('closes_at')), _connector='OR'), name='leai_survey_occurrence_schedule_ordered'),
        ),
        migrations.AddConstraint(
            model_name='questionsettemplaterevision',
            constraint=models.UniqueConstraint(fields=('template', 'revision_number'), name='leai_template_revision_number_uniq'),
        ),
        migrations.AddConstraint(
            model_name='questionsettemplaterevision',
            constraint=models.CheckConstraint(check=models.Q(('content_hash__regex', '^[0-9a-f]{64}$')), name='leai_template_revision_hash_valid'),
        ),
        migrations.AddConstraint(
            model_name='questionsettemplate',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('owner_account__isnull', False), ('owner_institution__isnull', True)), models.Q(('owner_account__isnull', True), ('owner_institution__isnull', False)), _connector='OR'), name='leai_question_set_template_owner_scope_xor'),
        ),
        migrations.AddConstraint(
            model_name='previewsession',
            constraint=models.CheckConstraint(check=models.Q(('capability_digest__regex', '^[0-9a-f]{64}$')), name='leai_preview_session_capability_digest_valid'),
        ),
        migrations.AddConstraint(
            model_name='previewmessage',
            constraint=models.UniqueConstraint(fields=('preview_session', 'sequence'), name='leai_preview_message_sequence_uniq'),
        ),
        migrations.AddConstraint(
            model_name='previewmessage',
            constraint=models.CheckConstraint(check=models.Q(('role__in', ['student', 'assistant', 'system'])), name='leai_preview_message_role_valid'),
        ),
        migrations.AddConstraint(
            model_name='previewdecision',
            constraint=models.CheckConstraint(check=models.Q(('decision__in', ['completed', 'skipped'])), name='leai_preview_decision_valid'),
        ),
        migrations.AddConstraint(
            model_name='previewdecision',
            constraint=models.CheckConstraint(check=models.Q(('idempotency_key_hash__regex', '^[0-9a-f]{64}$')), name='leai_preview_decision_idempotency_hash_valid'),
        ),
        migrations.AddConstraint(
            model_name='authoringrun',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['pending', 'running', 'succeeded', 'failed', 'canceled'])), name='leai_authoring_run_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='authoringrun',
            constraint=models.CheckConstraint(check=models.Q(('source_provenance_snapshot__isnull', False)), name='leai_authoring_run_provenance_present'),
        ),
        migrations.AddConstraint(
            model_name='authoringmessage',
            constraint=models.UniqueConstraint(fields=('conversation', 'sequence'), name='leai_authoring_message_sequence_uniq'),
        ),
        migrations.AddConstraint(
            model_name='authoringmessage',
            constraint=models.CheckConstraint(check=models.Q(('role__in', ['user', 'assistant', 'system'])), name='leai_authoring_message_role_valid'),
        ),
        migrations.AddConstraint(
            model_name='authoringmessage',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('input_method__in', ['typed', 'voice']), ('input_method__isnull', False), ('role', 'user')), models.Q(('input_method__isnull', True), ('role__in', ['assistant', 'system'])), _connector='OR'), name='leai_authoring_message_input_shape_valid'),
        ),
        migrations.AddConstraint(
            model_name='authoringconversation',
            constraint=models.CheckConstraint(check=models.Q(('origin_surface__in', ['builder', 'instructor_insights', 'survey_list', 'template'])), name='leai_authoring_conversation_origin_valid'),
        ),
        migrations.RunSQL(
            sql="""
                ALTER TABLE leai_authoringrun
                    ADD CONSTRAINT leai_authoring_run_provenance_object_bounded
                    CHECK (
                        jsonb_typeof(source_provenance_snapshot) = 'object'
                        AND pg_column_size(source_provenance_snapshot) <= 16384
                    );

                ALTER TABLE leai_questionsettemplate
                    ALTER COLUMN public_id SET DEFAULT gen_random_uuid();
                ALTER TABLE leai_questionsettemplaterevision
                    ALTER COLUMN public_id SET DEFAULT gen_random_uuid();
                ALTER TABLE leai_previewsession
                    ALTER COLUMN public_id SET DEFAULT gen_random_uuid();
                ALTER TABLE leai_surveyoccurrence
                    ALTER COLUMN public_id SET DEFAULT gen_random_uuid();

                CREATE FUNCTION leai_reject_publication_public_id_update()
                RETURNS TRIGGER AS $$
                BEGIN
                    IF NEW.public_id IS DISTINCT FROM OLD.public_id THEN
                        RAISE EXCEPTION USING
                            ERRCODE = '23514',
                            MESSAGE = 'LEAI publication public_id values are immutable';
                    END IF;
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER leai_questionsettemplate_public_id_immutable
                BEFORE UPDATE OF public_id ON leai_questionsettemplate
                FOR EACH ROW EXECUTE FUNCTION leai_reject_publication_public_id_update();

                CREATE TRIGGER leai_questionsettemplaterevision_public_id_immutable
                BEFORE UPDATE OF public_id ON leai_questionsettemplaterevision
                FOR EACH ROW EXECUTE FUNCTION leai_reject_publication_public_id_update();

                CREATE TRIGGER leai_previewsession_public_id_immutable
                BEFORE UPDATE OF public_id ON leai_previewsession
                FOR EACH ROW EXECUTE FUNCTION leai_reject_publication_public_id_update();

                CREATE TRIGGER leai_surveyoccurrence_public_id_immutable
                BEFORE UPDATE OF public_id ON leai_surveyoccurrence
                FOR EACH ROW EXECUTE FUNCTION leai_reject_publication_public_id_update();

                CREATE FUNCTION leai_reject_immutable_template_revision()
                RETURNS TRIGGER AS $$
                BEGIN
                    RAISE EXCEPTION USING
                        ERRCODE = '23514',
                        MESSAGE = 'Template revisions are immutable';
                END;
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER leai_questionsettemplaterevision_immutable
                BEFORE UPDATE OR DELETE ON leai_questionsettemplaterevision
                FOR EACH ROW EXECUTE FUNCTION leai_reject_immutable_template_revision();

                CREATE FUNCTION leai_reject_immutable_preview_decision()
                RETURNS TRIGGER AS $$
                BEGIN
                    RAISE EXCEPTION USING
                        ERRCODE = '23514',
                        MESSAGE = 'Preview decisions are immutable';
                END;
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER leai_previewdecision_immutable
                BEFORE UPDATE OR DELETE ON leai_previewdecision
                FOR EACH ROW EXECUTE FUNCTION leai_reject_immutable_preview_decision();

                CREATE FUNCTION leai_reject_survey_occurrence_identity_update()
                RETURNS TRIGGER AS $$
                BEGIN
                    IF NEW.public_id IS DISTINCT FROM OLD.public_id
                       OR NEW.revision_id IS DISTINCT FROM OLD.revision_id
                       OR NEW.course_id IS DISTINCT FROM OLD.course_id
                       OR NEW.created_by_id IS DISTINCT FROM OLD.created_by_id
                       OR NEW.provenance IS DISTINCT FROM OLD.provenance
                       OR NEW.management_mode IS DISTINCT FROM OLD.management_mode THEN
                        RAISE EXCEPTION USING
                            ERRCODE = '23514',
                            MESSAGE = 'Survey Occurrence identity is immutable';
                    END IF;
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER leai_a_surveyoccurrence_identity_immutable
                BEFORE UPDATE OF public_id, revision_id, course_id, created_by_id,
                    provenance, management_mode ON leai_surveyoccurrence
                FOR EACH ROW EXECUTE FUNCTION leai_reject_survey_occurrence_identity_update();

                CREATE FUNCTION leai_enforce_authoring_run_base_draft_version()
                RETURNS TRIGGER AS $$
                DECLARE
                    conversation_question_set_id bigint;
                    source_question_set_id bigint;
                BEGIN
                    SELECT question_set_id
                    INTO conversation_question_set_id
                    FROM leai_authoringconversation
                    WHERE id = NEW.conversation_id
                    FOR UPDATE;

                    SELECT draft.question_set_id
                    INTO source_question_set_id
                    FROM leai_questionsetdraftversion AS source_version
                    JOIN leai_questionsetdraft AS draft ON draft.id = source_version.draft_id
                    WHERE source_version.id = NEW.base_draft_version_id
                    FOR UPDATE OF source_version, draft;

                    PERFORM 1
                    FROM leai_questionset
                    WHERE id IN (conversation_question_set_id, source_question_set_id)
                    ORDER BY id
                    FOR UPDATE;

                    IF conversation_question_set_id IS NULL
                       OR source_question_set_id IS NULL
                       OR conversation_question_set_id <> source_question_set_id THEN
                        RAISE EXCEPTION USING
                            ERRCODE = '23514',
                            MESSAGE = 'Authoring Run base draft version must belong to its Conversation Question Set';
                    END IF;
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER leai_authoringrun_base_draft_version_same_question_set
                BEFORE INSERT OR UPDATE OF conversation_id, base_draft_version_id
                ON leai_authoringrun
                FOR EACH ROW EXECUTE FUNCTION leai_enforce_authoring_run_base_draft_version();

                CREATE FUNCTION leai_enforce_conversation_question_set_update()
                RETURNS TRIGGER AS $$
                DECLARE
                    run_question_set_id bigint;
                BEGIN
                    FOR run_question_set_id IN
                        SELECT draft.question_set_id
                        FROM leai_authoringrun AS authoring_run
                        JOIN leai_questionsetdraftversion AS source_version
                          ON source_version.id = authoring_run.base_draft_version_id
                        JOIN leai_questionsetdraft AS draft ON draft.id = source_version.draft_id
                        WHERE authoring_run.conversation_id = NEW.id
                    LOOP
                        IF NEW.question_set_id <> run_question_set_id THEN
                            RAISE EXCEPTION USING
                                ERRCODE = '23514',
                                MESSAGE = 'Authoring Conversation question_set must match dependent Run base draft versions';
                        END IF;
                    END LOOP;
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER leai_authoringconversation_question_set_lineage_valid
                BEFORE UPDATE OF question_set_id ON leai_authoringconversation
                FOR EACH ROW EXECUTE FUNCTION leai_enforce_conversation_question_set_update();

                CREATE FUNCTION leai_enforce_template_source_revision()
                RETURNS TRIGGER AS $$
                DECLARE
                    template_owner_account_id bigint;
                    template_owner_institution_id bigint;
                    source_owner_account_id bigint;
                    source_institution_id bigint;
                BEGIN
                    IF NEW.source_question_set_revision_id IS NULL THEN
                        RETURN NEW;
                    END IF;

                    SELECT owner_account_id, owner_institution_id
                    INTO template_owner_account_id, template_owner_institution_id
                    FROM leai_questionsettemplate
                    WHERE id = NEW.template_id
                    FOR UPDATE;

                    SELECT question_set.owner_id, course.institution_id
                    INTO source_owner_account_id, source_institution_id
                    FROM leai_questionsetrevision AS source_revision
                    JOIN leai_questionset AS question_set
                      ON question_set.id = source_revision.question_set_id
                    JOIN leai_course AS course ON course.id = question_set.course_id
                    WHERE source_revision.id = NEW.source_question_set_revision_id
                    FOR UPDATE OF source_revision, question_set, course;

                    IF template_owner_account_id IS NULL AND template_owner_institution_id IS NULL
                       OR source_owner_account_id IS NULL THEN
                        RAISE EXCEPTION USING
                            ERRCODE = '23514',
                            MESSAGE = 'Template source revision must match its owner scope';
                    END IF;

                    IF (template_owner_account_id IS NOT NULL
                        AND template_owner_account_id <> source_owner_account_id)
                       OR (template_owner_institution_id IS NOT NULL
                           AND template_owner_institution_id <> source_institution_id) THEN
                        RAISE EXCEPTION USING
                            ERRCODE = '23514',
                            MESSAGE = 'Template source revision must match its owner scope';
                    END IF;
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER leai_template_revision_source_valid
                BEFORE INSERT OR UPDATE OF template_id, source_question_set_revision_id
                ON leai_questionsettemplaterevision
                FOR EACH ROW EXECUTE FUNCTION leai_enforce_template_source_revision();

                CREATE FUNCTION leai_enforce_template_owner_scope_update()
                RETURNS TRIGGER AS $$
                DECLARE
                    source_owner_account_id bigint;
                    source_institution_id bigint;
                BEGIN
                    FOR source_owner_account_id, source_institution_id IN
                        SELECT question_set.owner_id, course.institution_id
                        FROM leai_questionsettemplaterevision AS template_revision
                        JOIN leai_questionsetrevision AS source_revision
                          ON source_revision.id = template_revision.source_question_set_revision_id
                        JOIN leai_questionset AS question_set
                          ON question_set.id = source_revision.question_set_id
                        JOIN leai_course AS course ON course.id = question_set.course_id
                        WHERE template_revision.template_id = NEW.id
                        FOR UPDATE OF template_revision, source_revision, question_set, course
                    LOOP
                        IF (NEW.owner_account_id IS NOT NULL
                            AND NEW.owner_account_id <> source_owner_account_id)
                           OR (NEW.owner_institution_id IS NOT NULL
                               AND NEW.owner_institution_id <> source_institution_id) THEN
                            RAISE EXCEPTION USING
                                ERRCODE = '23514',
                                MESSAGE = 'Template source revision must match its owner scope';
                        END IF;
                    END LOOP;
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER leai_questionsettemplate_owner_scope_lineage_valid
                BEFORE UPDATE OF owner_account_id, owner_institution_id
                ON leai_questionsettemplate
                FOR EACH ROW EXECUTE FUNCTION leai_enforce_template_owner_scope_update();

                CREATE FUNCTION leai_enforce_course_institution_template_lineage()
                RETURNS TRIGGER AS $$
                DECLARE
                    template_institution_id bigint;
                BEGIN
                    FOR template_institution_id IN
                        SELECT template.owner_institution_id
                        FROM leai_questionsettemplaterevision AS template_revision
                        JOIN leai_questionsettemplate AS template
                          ON template.id = template_revision.template_id
                        JOIN leai_questionsetrevision AS source_revision
                          ON source_revision.id = template_revision.source_question_set_revision_id
                        JOIN leai_questionset AS question_set
                          ON question_set.id = source_revision.question_set_id
                        WHERE question_set.course_id = NEW.id
                          AND template.owner_institution_id IS NOT NULL
                    LOOP
                        IF NEW.institution_id <> template_institution_id THEN
                            RAISE EXCEPTION USING
                                ERRCODE = '23514',
                                MESSAGE = 'Course institution must match dependent institution template revisions';
                        END IF;
                    END LOOP;
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER leai_course_institution_template_lineage_valid
                BEFORE UPDATE OF institution_id ON leai_course
                FOR EACH ROW EXECUTE FUNCTION leai_enforce_course_institution_template_lineage();

                CREATE FUNCTION leai_enforce_survey_occurrence_course()
                RETURNS TRIGGER AS $$
                DECLARE
                    revision_course_id bigint;
                BEGIN
                    SELECT question_set.course_id
                    INTO revision_course_id
                    FROM leai_questionsetrevision AS revision
                    JOIN leai_questionset AS question_set
                      ON question_set.id = revision.question_set_id
                    WHERE revision.id = NEW.revision_id
                    FOR UPDATE OF revision, question_set;

                    PERFORM 1
                    FROM leai_course
                    WHERE id IN (NEW.course_id, revision_course_id)
                    ORDER BY id
                    FOR UPDATE;

                    IF revision_course_id IS NULL OR revision_course_id <> NEW.course_id THEN
                        RAISE EXCEPTION USING
                            ERRCODE = '23514',
                            MESSAGE = 'Survey Occurrence course must match its Revision Question Set course';
                    END IF;
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER leai_survey_occurrence_course_matches_revision
                BEFORE INSERT OR UPDATE OF revision_id, course_id
                ON leai_surveyoccurrence
                FOR EACH ROW EXECUTE FUNCTION leai_enforce_survey_occurrence_course();
            """,
            reverse_sql="""
                DROP TRIGGER IF EXISTS leai_survey_occurrence_course_matches_revision
                    ON leai_surveyoccurrence;
                DROP FUNCTION IF EXISTS leai_enforce_survey_occurrence_course();

                DROP TRIGGER IF EXISTS leai_template_revision_source_valid
                    ON leai_questionsettemplaterevision;
                DROP FUNCTION IF EXISTS leai_enforce_template_source_revision();

                DROP TRIGGER IF EXISTS leai_course_institution_template_lineage_valid
                    ON leai_course;
                DROP FUNCTION IF EXISTS leai_enforce_course_institution_template_lineage();

                DROP TRIGGER IF EXISTS leai_questionsettemplate_owner_scope_lineage_valid
                    ON leai_questionsettemplate;
                DROP FUNCTION IF EXISTS leai_enforce_template_owner_scope_update();

                DROP TRIGGER IF EXISTS leai_authoringrun_base_draft_version_same_question_set
                    ON leai_authoringrun;
                DROP FUNCTION IF EXISTS leai_enforce_authoring_run_base_draft_version();

                DROP TRIGGER IF EXISTS leai_authoringconversation_question_set_lineage_valid
                    ON leai_authoringconversation;
                DROP FUNCTION IF EXISTS leai_enforce_conversation_question_set_update();

                DROP TRIGGER IF EXISTS leai_a_surveyoccurrence_identity_immutable
                    ON leai_surveyoccurrence;
                DROP FUNCTION IF EXISTS leai_reject_survey_occurrence_identity_update();

                DROP TRIGGER IF EXISTS leai_previewdecision_immutable ON leai_previewdecision;
                DROP FUNCTION IF EXISTS leai_reject_immutable_preview_decision();

                DROP TRIGGER IF EXISTS leai_questionsettemplaterevision_immutable
                    ON leai_questionsettemplaterevision;
                DROP FUNCTION IF EXISTS leai_reject_immutable_template_revision();

                DROP TRIGGER IF EXISTS leai_surveyoccurrence_public_id_immutable
                    ON leai_surveyoccurrence;
                DROP TRIGGER IF EXISTS leai_previewsession_public_id_immutable
                    ON leai_previewsession;
                DROP TRIGGER IF EXISTS leai_questionsettemplaterevision_public_id_immutable
                    ON leai_questionsettemplaterevision;
                DROP TRIGGER IF EXISTS leai_questionsettemplate_public_id_immutable
                    ON leai_questionsettemplate;
                DROP FUNCTION IF EXISTS leai_reject_publication_public_id_update();

                ALTER TABLE leai_surveyoccurrence ALTER COLUMN public_id DROP DEFAULT;
                ALTER TABLE leai_previewsession ALTER COLUMN public_id DROP DEFAULT;
                ALTER TABLE leai_questionsettemplaterevision ALTER COLUMN public_id DROP DEFAULT;
                ALTER TABLE leai_questionsettemplate ALTER COLUMN public_id DROP DEFAULT;

                ALTER TABLE leai_authoringrun
                    DROP CONSTRAINT IF EXISTS leai_authoring_run_provenance_object_bounded;
            """,
        ),
    ]
