# Generated by Django 4.2.7 on 2026-09-22 18:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('leai', '0005_authoring_publication'),
    ]

    operations = [
        migrations.CreateModel(
            name='PdfImportBatch',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('idempotency_key_hash', models.CharField(max_length=64)),
                ('manifest_digest', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('prepared', 'Prepared'), ('committed', 'Committed'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='prepared', max_length=16)),
                ('manifest', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('committed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='committed_pdf_import_batches', to='leai.instructoraccount')),
                ('occurrence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pdf_import_batches', to='leai.surveyoccurrence')),
            ],
        ),
        migrations.CreateModel(
            name='TeamConfiguration',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('settings_version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_configurations', to='leai.course')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_team_configurations', to='leai.instructoraccount')),
            ],
        ),
        migrations.CreateModel(
            name='TeamSnapshot',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('frozen_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_snapshots', to='leai.course')),
                ('occurrence', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='team_snapshot', to='leai.surveyoccurrence')),
                ('source_configuration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snapshots', to='leai.teamconfiguration')),
            ],
        ),
        migrations.CreateModel(
            name='TeamSnapshotItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item_number', models.PositiveIntegerField()),
                ('stable_key', models.CharField(max_length=64)),
                ('label', models.CharField(max_length=200)),
                ('occurrence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_snapshot_items', to='leai.surveyoccurrence')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='leai.teamsnapshot')),
            ],
        ),
        migrations.CreateModel(
            name='TeamDefinition',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('stable_key', models.CharField(max_length=64)),
                ('label', models.CharField(max_length=200)),
                ('sort_order', models.PositiveIntegerField()),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='definitions', to='leai.teamconfiguration')),
            ],
        ),
        migrations.CreateModel(
            name='ResponseSession',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('capability_nonce', models.CharField(blank=True, max_length=128, null=True)),
                ('capability_digest', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('capability_key_version', models.PositiveIntegerField(blank=True, null=True)),
                ('source', models.CharField(choices=[('student', 'Student'), ('pdf', 'PDF')], max_length=16)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('closed', 'Closed')], default='active', max_length=16)),
                ('research_consent', models.BooleanField(default=False)),
                ('next_message_sequence', models.PositiveIntegerField(default=1)),
                ('turn_version', models.PositiveIntegerField(default=1)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completion_snapshot', models.JSONField(blank=True, null=True)),
                ('certificate_code', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('certificate_issued_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('occurrence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='response_sessions', to='leai.surveyoccurrence')),
                ('pdf_import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='response_sessions', to='leai.pdfimportbatch')),
                ('team_snapshot_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='response_sessions', to='leai.teamsnapshotitem')),
            ],
        ),
        migrations.CreateModel(
            name='ResponseMessage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField()),
                ('role', models.CharField(choices=[('student', 'Student'), ('assistant', 'Assistant'), ('system', 'System')], max_length=16)),
                ('input_method', models.CharField(blank=True, choices=[('typed', 'Typed'), ('voice', 'Voice')], max_length=16, null=True)),
                ('content', models.TextField()),
                ('attribution', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('response_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='leai.responsesession')),
            ],
        ),
        migrations.CreateModel(
            name='PdfImportJob',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('job_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('result', models.JSONField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='leai.pdfimportbatch')),
            ],
        ),
        migrations.AddConstraint(
            model_name='teamsnapshotitem',
            constraint=models.UniqueConstraint(fields=('snapshot', 'item_number'), name='leai_team_snapshot_item_number_uniq'),
        ),
        migrations.AddConstraint(
            model_name='teamsnapshotitem',
            constraint=models.UniqueConstraint(fields=('snapshot', 'stable_key'), name='leai_team_snapshot_item_stable_key_uniq'),
        ),
        migrations.AddConstraint(
            model_name='teamsnapshotitem',
            constraint=models.UniqueConstraint(fields=('id', 'occurrence'), name='leai_team_snapshot_item_id_occurrence_uniq'),
        ),
        migrations.AddConstraint(
            model_name='teamsnapshotitem',
            constraint=models.CheckConstraint(check=models.Q(('item_number__gte', 1)), name='leai_team_snapshot_item_number_positive'),
        ),
        migrations.AddConstraint(
            model_name='teamsnapshot',
            constraint=models.UniqueConstraint(fields=('id', 'occurrence'), name='leai_team_snapshot_id_occurrence_uniq'),
        ),
        migrations.AddConstraint(
            model_name='teamdefinition',
            constraint=models.UniqueConstraint(fields=('configuration', 'stable_key'), name='leai_team_definition_stable_key_uniq'),
        ),
        migrations.AddConstraint(
            model_name='teamdefinition',
            constraint=models.UniqueConstraint(fields=('configuration', 'sort_order'), name='leai_team_definition_sort_order_uniq'),
        ),
        migrations.AddConstraint(
            model_name='teamconfiguration',
            constraint=models.UniqueConstraint(fields=('id', 'course'), name='leai_team_configuration_id_course_uniq'),
        ),
        migrations.AddConstraint(
            model_name='teamconfiguration',
            constraint=models.CheckConstraint(check=models.Q(('settings_version__gte', 1)), name='leai_team_configuration_settings_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='responsesession',
            constraint=models.CheckConstraint(check=models.Q(('source__in', ['student', 'pdf'])), name='leai_response_session_source_valid'),
        ),
        migrations.AddConstraint(
            model_name='responsesession',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['active', 'completed', 'closed'])), name='leai_response_session_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='responsesession',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('capability_digest__isnull', False), ('capability_key_version__isnull', False), ('capability_nonce__isnull', False), ('pdf_import_batch__isnull', True), ('source', 'student')), models.Q(('capability_digest__isnull', True), ('capability_key_version__isnull', True), ('capability_nonce__isnull', True), ('pdf_import_batch__isnull', False), ('source', 'pdf')), _connector='OR'), name='leai_response_session_source_shape_valid'),
        ),
        migrations.AddConstraint(
            model_name='responsesession',
            constraint=models.CheckConstraint(check=models.Q(('capability_nonce__isnull', True), models.Q(('capability_nonce', ''), _negated=True), _connector='OR'), name='leai_response_session_capability_nonce_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='responsesession',
            constraint=models.CheckConstraint(check=models.Q(('capability_digest__isnull', True), ('capability_digest__regex', '^[0-9a-f]{64}$'), _connector='OR'), name='leai_response_session_capability_digest_valid'),
        ),
        migrations.AddConstraint(
            model_name='responsesession',
            constraint=models.CheckConstraint(check=models.Q(('capability_key_version__isnull', True), ('capability_key_version__gte', 1), _connector='OR'), name='leai_response_session_capability_key_positive'),
        ),
        migrations.AddConstraint(
            model_name='responsesession',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('completed_at__isnull', True), ('completion_snapshot__isnull', True)), models.Q(('completed_at__isnull', False), ('completion_snapshot__isnull', False)), _connector='OR'), name='leai_response_session_completion_shape_valid'),
        ),
        migrations.AddConstraint(
            model_name='responsesession',
            constraint=models.CheckConstraint(check=models.Q(('next_message_sequence__gte', 1)), name='leai_response_session_next_sequence_positive'),
        ),
        migrations.AddConstraint(
            model_name='responsesession',
            constraint=models.CheckConstraint(check=models.Q(('turn_version__gte', 1)), name='leai_response_session_turn_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='responsemessage',
            constraint=models.UniqueConstraint(fields=('response_session', 'sequence'), name='leai_response_message_sequence_uniq'),
        ),
        migrations.AddConstraint(
            model_name='responsemessage',
            constraint=models.CheckConstraint(check=models.Q(('sequence__gte', 1)), name='leai_response_message_sequence_positive'),
        ),
        migrations.AddConstraint(
            model_name='responsemessage',
            constraint=models.CheckConstraint(check=models.Q(('role__in', ['student', 'assistant', 'system'])), name='leai_response_message_role_valid'),
        ),
        migrations.AddConstraint(
            model_name='responsemessage',
            constraint=models.CheckConstraint(check=models.Q(('input_method__isnull', True), models.Q(('input_method__in', ['typed', 'voice']), ('role', 'student')), _connector='OR'), name='leai_response_message_input_shape_valid'),
        ),
        migrations.AddConstraint(
            model_name='pdfimportjob',
            constraint=models.UniqueConstraint(fields=('batch', 'job_number'), name='leai_pdf_import_job_number_uniq'),
        ),
        migrations.AddConstraint(
            model_name='pdfimportjob',
            constraint=models.CheckConstraint(check=models.Q(('job_number__gte', 1)), name='leai_pdf_import_job_number_positive'),
        ),
        migrations.AddConstraint(
            model_name='pdfimportjob',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['pending', 'running', 'completed', 'failed'])), name='leai_pdf_import_job_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='pdfimportbatch',
            constraint=models.UniqueConstraint(fields=('id', 'occurrence'), name='leai_pdf_import_batch_id_occurrence_uniq'),
        ),
        migrations.AddConstraint(
            model_name='pdfimportbatch',
            constraint=models.UniqueConstraint(fields=('occurrence', 'idempotency_key_hash'), name='leai_pdf_import_batch_occurrence_idempotency_uniq'),
        ),
        migrations.AddConstraint(
            model_name='pdfimportbatch',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['prepared', 'committed', 'processing', 'completed', 'failed'])), name='leai_pdf_import_batch_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='pdfimportbatch',
            constraint=models.CheckConstraint(check=models.Q(('idempotency_key_hash__regex', '^[0-9a-f]{64}$')), name='leai_pdf_import_batch_idempotency_hash_valid'),
        ),
        migrations.AddConstraint(
            model_name='pdfimportbatch',
            constraint=models.CheckConstraint(check=models.Q(('manifest_digest__regex', '^[0-9a-f]{64}$')), name='leai_pdf_import_batch_manifest_digest_valid'),
        ),
        migrations.RunSQL(
            sql="""
                ALTER TABLE leai_responsemessage
                    ADD CONSTRAINT leai_response_message_attribution_bounded
                    CHECK (
                        jsonb_typeof(attribution) = 'object'
                        AND pg_column_size(attribution) <= 16384
                    );

                ALTER TABLE leai_pdfimportjob
                    ADD CONSTRAINT leai_pdf_import_job_result_bounded
                    CHECK (
                        result IS NULL
                        OR (
                            jsonb_typeof(result) = 'object'
                            AND pg_column_size(result) <= 16384
                        )
                    );

                ALTER TABLE leai_pdfimportbatch
                    ALTER COLUMN public_id SET DEFAULT gen_random_uuid();
                ALTER TABLE leai_responsesession
                    ALTER COLUMN public_id SET DEFAULT gen_random_uuid();

                ALTER TABLE leai_surveyoccurrence
                    ADD CONSTRAINT leai_survey_occurrence_id_course_uniq
                    UNIQUE (id, course_id);

                CREATE FUNCTION leai_reject_response_identity_update()
                RETURNS TRIGGER AS $$
                BEGIN
                    IF NEW.public_id IS DISTINCT FROM OLD.public_id
                       OR NEW.occurrence_id IS DISTINCT FROM OLD.occurrence_id THEN
                        RAISE EXCEPTION USING
                            ERRCODE = '23514',
                            MESSAGE = 'LEAI response public_id and occurrence values are immutable';
                    END IF;
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER leai_pdfimportbatch_identity_immutable
                BEFORE UPDATE OF public_id, occurrence_id ON leai_pdfimportbatch
                FOR EACH ROW EXECUTE FUNCTION leai_reject_response_identity_update();

                CREATE TRIGGER leai_responsesession_identity_immutable
                BEFORE UPDATE OF public_id, occurrence_id ON leai_responsesession
                FOR EACH ROW EXECUTE FUNCTION leai_reject_response_identity_update();

                CREATE FUNCTION leai_reject_team_configuration_course_update()
                RETURNS TRIGGER AS $$
                BEGIN
                    IF NEW.course_id IS DISTINCT FROM OLD.course_id THEN
                        RAISE EXCEPTION USING
                            ERRCODE = '23514',
                            MESSAGE = 'Team Configuration course is immutable';
                    END IF;
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER leai_team_configuration_course_immutable
                BEFORE UPDATE OF course_id ON leai_teamconfiguration
                FOR EACH ROW EXECUTE FUNCTION leai_reject_team_configuration_course_update();

                CREATE FUNCTION leai_guard_team_snapshot_mutation()
                RETURNS TRIGGER AS $$
                BEGIN
                    IF TG_OP = 'UPDATE'
                       AND OLD.frozen_at IS NULL
                       AND NEW.frozen_at IS NOT NULL
                       AND NEW.id IS NOT DISTINCT FROM OLD.id
                       AND NEW.occurrence_id IS NOT DISTINCT FROM OLD.occurrence_id
                       AND NEW.source_configuration_id IS NOT DISTINCT FROM OLD.source_configuration_id
                       AND NEW.course_id IS NOT DISTINCT FROM OLD.course_id THEN
                        RETURN NEW;
                    END IF;
                    RAISE EXCEPTION USING
                        ERRCODE = '23514',
                        MESSAGE = 'LEAI Team Snapshot rows are immutable after freezing';
                END;
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER leai_team_snapshot_immutable
                BEFORE UPDATE OR DELETE ON leai_teamsnapshot
                FOR EACH ROW EXECUTE FUNCTION leai_guard_team_snapshot_mutation();

                CREATE FUNCTION leai_require_team_snapshot_frozen()
                RETURNS TRIGGER AS $$
                BEGIN
                    PERFORM 1
                    FROM leai_teamsnapshot
                    WHERE id = NEW.id AND frozen_at IS NOT NULL;
                    IF NOT FOUND THEN
                        RAISE EXCEPTION USING
                            ERRCODE = '23514',
                            MESSAGE = 'LEAI Team Snapshot construction must freeze before commit';
                    END IF;
                    RETURN NULL;
                END;
                $$ LANGUAGE plpgsql;

                CREATE CONSTRAINT TRIGGER leai_team_snapshot_frozen_at_commit
                AFTER INSERT OR UPDATE ON leai_teamsnapshot
                DEFERRABLE INITIALLY DEFERRED
                FOR EACH ROW EXECUTE FUNCTION leai_require_team_snapshot_frozen();

                CREATE FUNCTION leai_reject_late_team_snapshot_item()
                RETURNS TRIGGER AS $$
                DECLARE
                    snapshot_frozen_at timestamp with time zone;
                BEGIN
                    SELECT frozen_at
                    INTO snapshot_frozen_at
                    FROM leai_teamsnapshot
                    WHERE id = NEW.snapshot_id;

                    IF NOT FOUND OR snapshot_frozen_at IS NOT NULL THEN
                        RAISE EXCEPTION USING
                            ERRCODE = '23514',
                            MESSAGE = 'LEAI Team Snapshot items may only be inserted during construction';
                    END IF;
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER leai_team_snapshot_item_construction_only
                BEFORE INSERT ON leai_teamsnapshotitem
                FOR EACH ROW EXECUTE FUNCTION leai_reject_late_team_snapshot_item();

                CREATE FUNCTION leai_reject_frozen_team_row_mutation()
                RETURNS TRIGGER AS $$
                BEGIN
                    RAISE EXCEPTION USING
                        ERRCODE = '23514',
                        MESSAGE = 'LEAI Team Snapshot rows are immutable and append-only';
                END;
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER leai_team_snapshot_item_immutable
                BEFORE UPDATE OR DELETE ON leai_teamsnapshotitem
                FOR EACH ROW EXECUTE FUNCTION leai_reject_frozen_team_row_mutation();

                ALTER TABLE leai_teamsnapshot
                    ADD CONSTRAINT leai_team_snapshot_occurrence_course_fk
                    FOREIGN KEY (occurrence_id, course_id)
                    REFERENCES leai_surveyoccurrence (id, course_id)
                    DEFERRABLE INITIALLY DEFERRED;

                ALTER TABLE leai_teamsnapshot
                    ADD CONSTRAINT leai_team_snapshot_configuration_course_fk
                    FOREIGN KEY (source_configuration_id, course_id)
                    REFERENCES leai_teamconfiguration (id, course_id)
                    DEFERRABLE INITIALLY DEFERRED;

                ALTER TABLE leai_teamsnapshotitem
                    ADD CONSTRAINT leai_team_snapshot_item_occurrence_fk
                    FOREIGN KEY (snapshot_id, occurrence_id)
                    REFERENCES leai_teamsnapshot (id, occurrence_id)
                    DEFERRABLE INITIALLY DEFERRED;

                ALTER TABLE leai_responsesession
                    ADD CONSTRAINT leai_response_session_team_occurrence_fk
                    FOREIGN KEY (team_snapshot_item_id, occurrence_id)
                    REFERENCES leai_teamsnapshotitem (id, occurrence_id)
                    DEFERRABLE INITIALLY DEFERRED;

                ALTER TABLE leai_responsesession
                    ADD CONSTRAINT leai_response_session_pdf_occurrence_fk
                    FOREIGN KEY (pdf_import_batch_id, occurrence_id)
                    REFERENCES leai_pdfimportbatch (id, occurrence_id)
                    DEFERRABLE INITIALLY DEFERRED;
            """,
            reverse_sql="""
                ALTER TABLE leai_responsesession
                    DROP CONSTRAINT IF EXISTS leai_response_session_pdf_occurrence_fk;
                ALTER TABLE leai_responsesession
                    DROP CONSTRAINT IF EXISTS leai_response_session_team_occurrence_fk;
                ALTER TABLE leai_teamsnapshotitem
                    DROP CONSTRAINT IF EXISTS leai_team_snapshot_item_occurrence_fk;
                ALTER TABLE leai_teamsnapshot
                    DROP CONSTRAINT IF EXISTS leai_team_snapshot_configuration_course_fk;
                ALTER TABLE leai_teamsnapshot
                    DROP CONSTRAINT IF EXISTS leai_team_snapshot_occurrence_course_fk;

                DROP TRIGGER IF EXISTS leai_team_snapshot_item_construction_only
                    ON leai_teamsnapshotitem;
                DROP FUNCTION IF EXISTS leai_reject_late_team_snapshot_item();

                DROP TRIGGER IF EXISTS leai_team_snapshot_frozen_at_commit
                    ON leai_teamsnapshot;
                DROP FUNCTION IF EXISTS leai_require_team_snapshot_frozen();

                DROP TRIGGER IF EXISTS leai_team_snapshot_item_immutable
                    ON leai_teamsnapshotitem;
                DROP TRIGGER IF EXISTS leai_team_snapshot_immutable
                    ON leai_teamsnapshot;
                DROP FUNCTION IF EXISTS leai_guard_team_snapshot_mutation();
                DROP FUNCTION IF EXISTS leai_reject_frozen_team_row_mutation();

                ALTER TABLE leai_surveyoccurrence
                    DROP CONSTRAINT IF EXISTS leai_survey_occurrence_id_course_uniq;

                DROP TRIGGER IF EXISTS leai_team_configuration_course_immutable
                    ON leai_teamconfiguration;
                DROP FUNCTION IF EXISTS leai_reject_team_configuration_course_update();

                DROP TRIGGER IF EXISTS leai_responsesession_identity_immutable
                    ON leai_responsesession;
                DROP TRIGGER IF EXISTS leai_pdfimportbatch_identity_immutable
                    ON leai_pdfimportbatch;
                DROP FUNCTION IF EXISTS leai_reject_response_identity_update();

                ALTER TABLE leai_responsesession ALTER COLUMN public_id DROP DEFAULT;
                ALTER TABLE leai_pdfimportbatch ALTER COLUMN public_id DROP DEFAULT;

                ALTER TABLE leai_pdfimportjob
                    DROP CONSTRAINT IF EXISTS leai_pdf_import_job_result_bounded;
                ALTER TABLE leai_responsemessage
                    DROP CONSTRAINT IF EXISTS leai_response_message_attribution_bounded;
            """,
        ),
    ]
