# Generated by Django 4.2.7 on 2026-09-22

from django.db import migrations, models
from django.db.models.lookups import Exact, LessThanOrEqual


class Migration(migrations.Migration):
    dependencies = [
        ("leai", "0006_responses"),
    ]

    operations = [
        migrations.CreateModel(
            name="MutationReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("principal_scope", models.CharField(max_length=255)),
                ("operation", models.CharField(max_length=128)),
                ("target_key", models.CharField(max_length=255)),
                ("idempotency_key_hash", models.CharField(max_length=64)),
                ("request_hash", models.CharField(max_length=64)),
                ("result", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "principal_scope",
                            "operation",
                            "target_key",
                            "idempotency_key_hash",
                        ),
                        name="leai_mutation_receipt_scope_idempotency_uniq",
                    ),
                    models.CheckConstraint(
                        check=models.Q(("principal_scope", ""), _negated=True),
                        name="leai_mutation_receipt_principal_nonempty",
                    ),
                    models.CheckConstraint(
                        check=models.Q(("operation", ""), _negated=True),
                        name="leai_mutation_receipt_operation_nonempty",
                    ),
                    models.CheckConstraint(
                        check=models.Q(("target_key", ""), _negated=True),
                        name="leai_mutation_receipt_target_nonempty",
                    ),
                    models.CheckConstraint(
                        check=models.Q(
                            ("idempotency_key_hash__regex", "^[0-9a-f]{64}$")
                        ),
                        name="leai_mutation_receipt_idempotency_hash_valid",
                    ),
                    models.CheckConstraint(
                        check=models.Q(("request_hash__regex", "^[0-9a-f]{64}$")),
                        name="leai_mutation_receipt_request_hash_valid",
                    ),
                    models.CheckConstraint(
                        check=models.Q(
                            models.Q(
                                ("completed_at__isnull", True),
                                ("result__isnull", True),
                            ),
                            models.Q(
                                ("completed_at__isnull", False),
                                ("result__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="leai_mutation_receipt_completion_shape_valid",
                    ),
                ],
            },
        ),
        migrations.RunSQL(
            sql="""
                CREATE FUNCTION leai_jsonb_canonical_size(value jsonb)
                RETURNS bigint AS $$
                DECLARE
                    value_kind text;
                    total_bytes bigint;
                    entry record;
                BEGIN
                    value_kind := jsonb_typeof(value);
                    IF value_kind = 'object' THEN
                        total_bytes := 2;
                        FOR entry IN
                            SELECT key, item_value
                            FROM jsonb_each(value) AS items(key, item_value)
                        LOOP
                            IF total_bytes > 2 THEN
                                total_bytes := total_bytes + 1;
                            END IF;
                            total_bytes := total_bytes
                                + octet_length(convert_to(to_jsonb(entry.key)::text, 'UTF8'))
                                + 1
                                + leai_jsonb_canonical_size(entry.item_value);
                        END LOOP;
                        RETURN total_bytes;
                    ELSIF value_kind = 'array' THEN
                        total_bytes := 2;
                        FOR entry IN
                            SELECT item_value
                            FROM jsonb_array_elements(value) AS items(item_value)
                        LOOP
                            IF total_bytes > 2 THEN
                                total_bytes := total_bytes + 1;
                            END IF;
                            total_bytes := total_bytes
                                + leai_jsonb_canonical_size(entry.item_value);
                        END LOOP;
                        RETURN total_bytes;
                    END IF;
                    RETURN octet_length(convert_to(value::text, 'UTF8'));
                END;
                $$ LANGUAGE plpgsql IMMUTABLE STRICT;
            """,
            reverse_sql="DROP FUNCTION IF EXISTS leai_jsonb_canonical_size(jsonb);",
        ),
        migrations.AddConstraint(
            model_name="mutationreceipt",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("result__isnull", True),
                    Exact(
                        models.Func(
                            models.F("result"),
                            function="jsonb_typeof",
                            output_field=models.CharField(),
                        ),
                        models.Value("object"),
                    ),
                    _connector="OR",
                ),
                name="leai_mutation_receipt_result_object",
            ),
        ),
        migrations.AddConstraint(
            model_name="mutationreceipt",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("result__isnull", True),
                    LessThanOrEqual(
                        models.Func(
                            models.F("result"),
                            function="leai_jsonb_canonical_size",
                            output_field=models.BigIntegerField(),
                        ),
                        models.Value(16384),
                    ),
                    _connector="OR",
                ),
                name="leai_mutation_receipt_result_bounded",
            ),
        ),
        migrations.RunSQL(
            sql="""
                CREATE FUNCTION leai_require_mutation_receipt_complete()
                RETURNS TRIGGER AS $$
                BEGIN
                    PERFORM 1
                    FROM leai_mutationreceipt
                    WHERE id = NEW.id
                      AND result IS NOT NULL
                      AND completed_at IS NOT NULL;
                    IF NOT FOUND THEN
                        RAISE EXCEPTION USING
                            ERRCODE = '23514',
                            MESSAGE = 'LEAI Mutation Receipt must complete before commit';
                    END IF;
                    RETURN NULL;
                END;
                $$ LANGUAGE plpgsql;

                CREATE CONSTRAINT TRIGGER leai_mutation_receipt_complete_at_commit
                AFTER INSERT OR UPDATE ON leai_mutationreceipt
                DEFERRABLE INITIALLY DEFERRED
                FOR EACH ROW EXECUTE FUNCTION leai_require_mutation_receipt_complete();

                CREATE FUNCTION leai_guard_mutation_receipt_mutation()
                RETURNS TRIGGER AS $$
                BEGIN
                    IF TG_OP = 'UPDATE'
                       AND OLD.result IS NULL
                       AND OLD.completed_at IS NULL
                       AND NEW.result IS NOT NULL
                       AND NEW.completed_at IS NOT NULL
                       AND NEW.id IS NOT DISTINCT FROM OLD.id
                       AND NEW.principal_scope IS NOT DISTINCT FROM OLD.principal_scope
                       AND NEW.operation IS NOT DISTINCT FROM OLD.operation
                       AND NEW.target_key IS NOT DISTINCT FROM OLD.target_key
                       AND NEW.idempotency_key_hash IS NOT DISTINCT FROM OLD.idempotency_key_hash
                       AND NEW.request_hash IS NOT DISTINCT FROM OLD.request_hash
                       AND NEW.created_at IS NOT DISTINCT FROM OLD.created_at THEN
                        RETURN NEW;
                    END IF;
                    RAISE EXCEPTION USING
                        ERRCODE = '23514',
                        MESSAGE = 'LEAI Mutation Receipt rows are immutable after completion';
                END;
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER leai_mutation_receipt_immutable
                BEFORE UPDATE OR DELETE ON leai_mutationreceipt
                FOR EACH ROW EXECUTE FUNCTION leai_guard_mutation_receipt_mutation();
            """,
            reverse_sql="""
                DROP TRIGGER IF EXISTS leai_mutation_receipt_immutable
                    ON leai_mutationreceipt;
                DROP FUNCTION IF EXISTS leai_guard_mutation_receipt_mutation();
                DROP TRIGGER IF EXISTS leai_mutation_receipt_complete_at_commit
                    ON leai_mutationreceipt;
                DROP FUNCTION IF EXISTS leai_require_mutation_receipt_complete();
            """,
        ),
    ]
