# Generated by Django 4.2.7 on 2026-09-22 20:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('leai', '0007_mutation_receipt'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisChatMessage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField()),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=16)),
                ('input_method', models.CharField(blank=True, choices=[('typed', 'Typed'), ('voice', 'Voice')], max_length=16, null=True)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisChatSession',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('origin_surface', models.CharField(choices=[('feedback_chat', 'Feedback Chat'), ('instructor_insights', 'Instructor Insights'), ('analyzer', 'Analyzer')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analysis_chat_sessions', to='leai.instructoraccount')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analysis_chat_sessions', to='leai.course')),
            ],
        ),
        migrations.CreateModel(
            name='ImportRecordMap',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('source_environment', models.CharField(max_length=32)),
                ('target_environment', models.CharField(max_length=32)),
                ('source_model', models.CharField(max_length=128)),
                ('source_key', models.CharField(max_length=255)),
                ('source_row_digest', models.CharField(max_length=64)),
                ('target_model', models.CharField(max_length=128)),
                ('target_key', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImportRun',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('run_kind', models.CharField(choices=[('dry_run', 'Dry run'), ('execute', 'Execute')], max_length=16)),
                ('target_environment', models.CharField(max_length=32)),
                ('idempotency_key_hash', models.CharField(max_length=64)),
                ('manifest_digest', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('source_environment', models.CharField(max_length=32)),
                ('source_release', models.CharField(max_length=128)),
                ('target_release', models.CharField(max_length=128)),
                ('migration_set', models.CharField(max_length=255)),
                ('contract_version', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_runs', to='leai.instructoraccount')),
            ],
        ),
        migrations.CreateModel(
            name='ImportRecordOutcome',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('source_model', models.CharField(max_length=128)),
                ('source_key', models.CharField(max_length=255)),
                ('disposition', models.CharField(choices=[('mapped', 'Mapped'), ('reused', 'Reused'), ('quarantined', 'Quarantined'), ('excluded', 'Excluded'), ('regenerated', 'Regenerated')], max_length=16)),
                ('reason_code', models.CharField(choices=[('none', 'None'), ('unresolved_owner', 'Unresolved owner'), ('unresolved_course', 'Unresolved course'), ('unresolved_session', 'Unresolved session'), ('unresolved_scope', 'Unresolved scope'), ('unknown_consent', 'Unknown consent'), ('digest_conflict', 'Digest conflict'), ('source_excluded', 'Source excluded'), ('cache_regenerated', 'Cache regenerated')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('import_record_map', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reuse_outcomes', to='leai.importrecordmap')),
                ('import_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='record_outcomes', to='leai.importrun')),
            ],
        ),
        migrations.AddField(
            model_name='importrecordmap',
            name='first_import_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='first_created_record_maps', to='leai.importrun'),
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('actor_kind', models.CharField(choices=[('instructor', 'Instructor'), ('platform_admin', 'Platform Admin'), ('system', 'System'), ('import', 'Import')], max_length=32)),
                ('action', models.CharField(max_length=128)),
                ('outcome', models.CharField(choices=[('allowed', 'Allowed'), ('denied', 'Denied'), ('failed', 'Failed')], max_length=16)),
                ('target_type', models.CharField(max_length=64)),
                ('target_id', models.CharField(max_length=128)),
                ('request_id', models.CharField(blank=True, default='', max_length=128)),
                ('bounded_metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='leai.instructoraccount')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='leai.course')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisSnapshot',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('scope_key', models.CharField(max_length=255)),
                ('algorithm_version', models.CharField(max_length=64)),
                ('response_cutoff_version', models.PositiveBigIntegerField()),
                ('model_policy_version', models.CharField(max_length=64)),
                ('prompt_policy_version', models.CharField(max_length=64)),
                ('source_count', models.PositiveIntegerField()),
                ('result', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analysis_snapshots', to='leai.course')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisScopeOccurrence',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('analysis_chat_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='occurrence_scope', to='leai.analysischatsession')),
                ('survey_occurrence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analysis_chat_scopes', to='leai.surveyoccurrence')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisCitation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('claim_key', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis_chat_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='citations', to='leai.analysischatmessage')),
                ('analysis_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='citations', to='leai.analysissnapshot')),
                ('response_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analysis_citations', to='leai.responsemessage')),
                ('response_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analysis_citations', to='leai.responsesession')),
            ],
        ),
        migrations.AddField(
            model_name='analysischatmessage',
            name='analysis_chat_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='leai.analysischatsession'),
        ),
        migrations.AddField(
            model_name='authoringconversation',
            name='source_analysis_snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seeded_authoring_conversations', to='leai.analysissnapshot'),
        ),
        migrations.AddConstraint(
            model_name='importrun',
            constraint=models.UniqueConstraint(fields=('target_environment', 'idempotency_key_hash'), name='leai_import_run_target_idempotency_uniq'),
        ),
        migrations.AddConstraint(
            model_name='importrun',
            constraint=models.CheckConstraint(check=models.Q(('run_kind__in', ['dry_run', 'execute'])), name='leai_import_run_kind_valid'),
        ),
        migrations.AddConstraint(
            model_name='importrun',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['pending', 'running', 'completed', 'failed'])), name='leai_import_run_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='importrun',
            constraint=models.CheckConstraint(check=models.Q(('idempotency_key_hash__regex', '^[0-9a-f]{64}$')), name='leai_import_run_idempotency_hash_valid'),
        ),
        migrations.AddConstraint(
            model_name='importrun',
            constraint=models.CheckConstraint(check=models.Q(('manifest_digest__regex', '^[0-9a-f]{64}$')), name='leai_import_run_manifest_digest_valid'),
        ),
        migrations.AddConstraint(
            model_name='importrecordoutcome',
            constraint=models.UniqueConstraint(fields=('import_run', 'source_model', 'source_key'), name='leai_import_outcome_run_source_uniq'),
        ),
        migrations.AddConstraint(
            model_name='importrecordoutcome',
            constraint=models.CheckConstraint(check=models.Q(('disposition__in', ['mapped', 'reused', 'quarantined', 'excluded', 'regenerated'])), name='leai_import_outcome_disposition_valid'),
        ),
        migrations.AddConstraint(
            model_name='importrecordoutcome',
            constraint=models.CheckConstraint(check=models.Q(('reason_code__in', ['none', 'unresolved_owner', 'unresolved_course', 'unresolved_session', 'unresolved_scope', 'unknown_consent', 'digest_conflict', 'source_excluded', 'cache_regenerated'])), name='leai_import_outcome_reason_valid'),
        ),
        migrations.AddConstraint(
            model_name='importrecordoutcome',
            constraint=models.CheckConstraint(check=models.Q(('disposition', 'quarantined'), ('reason_code', 'none'), _negated=True), name='leai_import_outcome_quarantine_reason_required'),
        ),
        migrations.AddConstraint(
            model_name='importrecordmap',
            constraint=models.UniqueConstraint(fields=('source_environment', 'target_environment', 'source_model', 'source_key'), name='leai_import_record_map_source_uniq'),
        ),
        migrations.AddConstraint(
            model_name='importrecordmap',
            constraint=models.CheckConstraint(check=models.Q(('source_row_digest__regex', '^[0-9a-f]{64}$')), name='leai_import_record_map_digest_valid'),
        ),
        migrations.AddConstraint(
            model_name='auditevent',
            constraint=models.CheckConstraint(check=models.Q(('actor_kind__in', ['instructor', 'platform_admin', 'system', 'import'])), name='leai_audit_actor_kind_valid'),
        ),
        migrations.AddConstraint(
            model_name='auditevent',
            constraint=models.CheckConstraint(check=models.Q(('outcome__in', ['allowed', 'denied', 'failed'])), name='leai_audit_outcome_valid'),
        ),
        migrations.AddConstraint(
            model_name='auditevent',
            constraint=models.CheckConstraint(check=models.Q(('action', ''), _negated=True), name='leai_audit_action_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='auditevent',
            constraint=models.CheckConstraint(check=models.Q(('target_type', ''), _negated=True), name='leai_audit_target_type_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='auditevent',
            constraint=models.CheckConstraint(check=models.Q(('target_id', ''), _negated=True), name='leai_audit_target_id_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='analysissnapshot',
            constraint=models.UniqueConstraint(fields=('course', 'scope_key', 'algorithm_version', 'response_cutoff_version', 'model_policy_version', 'prompt_policy_version'), name='leai_analysis_snapshot_generation_uniq'),
        ),
        migrations.AddConstraint(
            model_name='analysissnapshot',
            constraint=models.CheckConstraint(check=models.Q(('scope_key', ''), _negated=True), name='leai_analysis_snapshot_scope_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='analysisscopeoccurrence',
            constraint=models.UniqueConstraint(fields=('analysis_chat_session', 'survey_occurrence'), name='leai_analysis_scope_occurrence_uniq'),
        ),
        migrations.AddConstraint(
            model_name='analysiscitation',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('analysis_chat_message__isnull', False), ('analysis_snapshot__isnull', True)), models.Q(('analysis_chat_message__isnull', True), ('analysis_snapshot__isnull', False)), _connector='OR'), name='leai_analysis_citation_owner_xor'),
        ),
        migrations.AddConstraint(
            model_name='analysiscitation',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('response_message__isnull', True), ('response_session__isnull', False)), models.Q(('response_message__isnull', False), ('response_session__isnull', True)), _connector='OR'), name='leai_analysis_citation_source_xor'),
        ),
        migrations.AddConstraint(
            model_name='analysiscitation',
            constraint=models.CheckConstraint(check=models.Q(('claim_key', ''), _negated=True), name='leai_analysis_citation_claim_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='analysischatsession',
            constraint=models.CheckConstraint(check=models.Q(('origin_surface__in', ['feedback_chat', 'instructor_insights', 'analyzer'])), name='leai_analysis_chat_origin_valid'),
        ),
        migrations.AddConstraint(
            model_name='analysischatmessage',
            constraint=models.UniqueConstraint(fields=('analysis_chat_session', 'sequence'), name='leai_analysis_chat_message_sequence_uniq'),
        ),
        migrations.AddConstraint(
            model_name='analysischatmessage',
            constraint=models.CheckConstraint(check=models.Q(('sequence__gte', 1)), name='leai_analysis_chat_message_sequence_positive'),
        ),
        migrations.AddConstraint(
            model_name='analysischatmessage',
            constraint=models.CheckConstraint(check=models.Q(('role__in', ['user', 'assistant', 'system'])), name='leai_analysis_chat_message_role_valid'),
        ),
        migrations.AddConstraint(
            model_name='analysischatmessage',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('input_method__in', ['typed', 'voice']), ('input_method__isnull', False), ('role', 'user')), models.Q(('input_method__isnull', True), ('role__in', ['assistant', 'system'])), _connector='OR'), name='leai_analysis_chat_message_input_shape_valid'),
        ),
        migrations.AddConstraint(
            model_name='authoringconversation',
            constraint=models.CheckConstraint(
                check=(
                    models.Q(origin_surface='instructor_insights', source_analysis_snapshot__isnull=False)
                    | (~models.Q(origin_surface='instructor_insights') & models.Q(source_analysis_snapshot__isnull=True))
                ),
                name='leai_authoring_conversation_source_shape_valid',
            ),
        ),
        migrations.RunSQL(
            sql="""
                ALTER TABLE leai_auditevent ALTER COLUMN event_id SET DEFAULT gen_random_uuid();
                ALTER TABLE leai_importrun ALTER COLUMN public_id SET DEFAULT gen_random_uuid();

                ALTER TABLE leai_auditevent ADD CONSTRAINT leai_audit_metadata_bounded_object
                    CHECK (jsonb_typeof(bounded_metadata) = 'object'
                           AND leai_jsonb_canonical_size(bounded_metadata) <= 4096);

                CREATE FUNCTION leai_reject_task6_append_only()
                RETURNS trigger AS $$
                BEGIN
                    RAISE EXCEPTION '% is append-only', TG_TABLE_NAME
                        USING ERRCODE = '23514';
                END;
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER leai_analysis_snapshot_append_only
                    BEFORE UPDATE OR DELETE ON leai_analysissnapshot
                    FOR EACH ROW EXECUTE FUNCTION leai_reject_task6_append_only();
                CREATE TRIGGER leai_analysis_citation_append_only
                    BEFORE UPDATE OR DELETE ON leai_analysiscitation
                    FOR EACH ROW EXECUTE FUNCTION leai_reject_task6_append_only();
                CREATE TRIGGER leai_audit_event_append_only
                    BEFORE UPDATE OR DELETE ON leai_auditevent
                    FOR EACH ROW EXECUTE FUNCTION leai_reject_task6_append_only();
                CREATE TRIGGER leai_import_record_map_append_only
                    BEFORE UPDATE OR DELETE ON leai_importrecordmap
                    FOR EACH ROW EXECUTE FUNCTION leai_reject_task6_append_only();
                CREATE TRIGGER leai_import_record_outcome_append_only
                    BEFORE UPDATE OR DELETE ON leai_importrecordoutcome
                    FOR EACH ROW EXECUTE FUNCTION leai_reject_task6_append_only();
                CREATE TRIGGER leai_response_message_append_only
                    BEFORE UPDATE OR DELETE ON leai_responsemessage
                    FOR EACH ROW EXECUTE FUNCTION leai_reject_task6_append_only();

                CREATE FUNCTION leai_reject_task6_public_uuid_update()
                RETURNS trigger AS $$
                BEGIN
                    IF TG_TABLE_NAME = 'leai_auditevent' THEN
                        IF NEW.event_id IS DISTINCT FROM OLD.event_id THEN
                            RAISE EXCEPTION 'LEAI audit event UUID is immutable'
                                USING ERRCODE = '23514';
                        END IF;
                    ELSIF NEW.public_id IS DISTINCT FROM OLD.public_id THEN
                        RAISE EXCEPTION 'LEAI import run UUID is immutable'
                            USING ERRCODE = '23514';
                    END IF;
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;
                CREATE TRIGGER leai_auditevent_uuid_immutable
                    BEFORE UPDATE OF event_id ON leai_auditevent
                    FOR EACH ROW EXECUTE FUNCTION leai_reject_task6_public_uuid_update();
                CREATE TRIGGER leai_importrun_uuid_immutable
                    BEFORE UPDATE OF public_id ON leai_importrun
                    FOR EACH ROW EXECUTE FUNCTION leai_reject_task6_public_uuid_update();

                CREATE FUNCTION leai_check_analysis_scope_course()
                RETURNS trigger AS $$
                DECLARE chat_course bigint; occurrence_course bigint;
                BEGIN
                    SELECT course_id INTO chat_course FROM leai_analysischatsession
                        WHERE id = NEW.analysis_chat_session_id;
                    SELECT course_id INTO occurrence_course FROM leai_surveyoccurrence
                        WHERE id = NEW.survey_occurrence_id;
                    IF chat_course IS NULL OR occurrence_course IS NULL
                       OR chat_course <> occurrence_course THEN
                        RAISE EXCEPTION 'Analysis scope must belong to chat course'
                            USING ERRCODE = '23514';
                    END IF;
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;
                CREATE TRIGGER leai_analysis_scope_same_course
                    BEFORE INSERT OR UPDATE ON leai_analysisscopeoccurrence
                    FOR EACH ROW EXECUTE FUNCTION leai_check_analysis_scope_course();

                CREATE FUNCTION leai_reject_analysis_scope_after_message()
                RETURNS trigger AS $$
                DECLARE scope_chat_id bigint; moved_chat_id bigint;
                BEGIN
                    IF TG_OP = 'INSERT' THEN
                        scope_chat_id := NEW.analysis_chat_session_id;
                    ELSIF TG_OP = 'DELETE' THEN
                        scope_chat_id := OLD.analysis_chat_session_id;
                    ELSE
                        scope_chat_id := OLD.analysis_chat_session_id;
                        moved_chat_id := NEW.analysis_chat_session_id;
                    END IF;
                    PERFORM id FROM leai_analysischatsession
                        WHERE id IN (scope_chat_id, moved_chat_id)
                        ORDER BY id FOR UPDATE;
                    IF EXISTS (
                        SELECT 1 FROM leai_analysischatmessage
                        WHERE analysis_chat_session_id = scope_chat_id
                    ) OR (moved_chat_id IS NOT NULL AND EXISTS (
                        SELECT 1 FROM leai_analysischatmessage
                        WHERE analysis_chat_session_id = moved_chat_id
                    )) THEN
                        RAISE EXCEPTION 'Analysis scope is frozen after first message'
                            USING ERRCODE = '23514';
                    END IF;
                    IF TG_OP = 'DELETE' THEN
                        RETURN OLD;
                    END IF;
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;
                CREATE TRIGGER leai_analysis_scope_frozen_after_message
                    BEFORE INSERT OR UPDATE OR DELETE ON leai_analysisscopeoccurrence
                    FOR EACH ROW EXECUTE FUNCTION leai_reject_analysis_scope_after_message();

                CREATE FUNCTION leai_lock_analysis_chat_for_message_insert()
                RETURNS trigger AS $$
                BEGIN
                    PERFORM 1 FROM leai_analysischatsession
                        WHERE id = NEW.analysis_chat_session_id FOR UPDATE;
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;
                CREATE TRIGGER leai_analysis_message_lock_parent
                    BEFORE INSERT ON leai_analysischatmessage
                    FOR EACH ROW EXECUTE FUNCTION leai_lock_analysis_chat_for_message_insert();

                CREATE FUNCTION leai_check_analysis_citation_course()
                RETURNS trigger AS $$
                DECLARE owner_course bigint; source_course bigint;
                BEGIN
                    IF NEW.analysis_snapshot_id IS NOT NULL THEN
                        SELECT course_id INTO owner_course FROM leai_analysissnapshot
                            WHERE id = NEW.analysis_snapshot_id;
                    ELSE
                        SELECT chat.course_id INTO owner_course
                        FROM leai_analysischatmessage AS message
                        JOIN leai_analysischatsession AS chat
                            ON chat.id = message.analysis_chat_session_id
                        WHERE message.id = NEW.analysis_chat_message_id;
                    END IF;
                    IF NEW.response_session_id IS NOT NULL THEN
                        SELECT occurrence.course_id INTO source_course
                        FROM leai_responsesession AS session
                        JOIN leai_surveyoccurrence AS occurrence
                            ON occurrence.id = session.occurrence_id
                        WHERE session.id = NEW.response_session_id;
                    ELSE
                        SELECT occurrence.course_id INTO source_course
                        FROM leai_responsemessage AS message
                        JOIN leai_responsesession AS session
                            ON session.id = message.response_session_id
                        JOIN leai_surveyoccurrence AS occurrence
                            ON occurrence.id = session.occurrence_id
                        WHERE message.id = NEW.response_message_id;
                    END IF;
                    IF owner_course IS NULL OR source_course IS NULL
                       OR owner_course <> source_course THEN
                        RAISE EXCEPTION 'Analysis citation source must belong to owner course'
                            USING ERRCODE = '23514';
                    END IF;
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;
                CREATE TRIGGER leai_analysis_citation_same_course
                    BEFORE INSERT ON leai_analysiscitation
                    FOR EACH ROW EXECUTE FUNCTION leai_check_analysis_citation_course();

                CREATE FUNCTION leai_check_authoring_snapshot_course()
                RETURNS trigger AS $$
                DECLARE question_course bigint; snapshot_course bigint;
                BEGIN
                    IF NEW.source_analysis_snapshot_id IS NULL THEN
                        RETURN NEW;
                    END IF;
                    SELECT course_id INTO question_course FROM leai_questionset
                        WHERE id = NEW.question_set_id;
                    SELECT course_id INTO snapshot_course FROM leai_analysissnapshot
                        WHERE id = NEW.source_analysis_snapshot_id;
                    IF question_course IS NULL OR snapshot_course IS NULL
                       OR question_course <> snapshot_course THEN
                        RAISE EXCEPTION 'Authoring source snapshot must belong to Question Set course'
                            USING ERRCODE = '23514';
                    END IF;
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;
                CREATE TRIGGER leai_authoring_source_snapshot_same_course
                    BEFORE INSERT OR UPDATE OF question_set_id, source_analysis_snapshot_id
                    ON leai_authoringconversation
                    FOR EACH ROW EXECUTE FUNCTION leai_check_authoring_snapshot_course();

                CREATE FUNCTION leai_reject_authoring_conversation_identity_update()
                RETURNS trigger AS $$
                BEGIN
                    IF (NEW.created_by_id, NEW.question_set_id,
                        NEW.source_analysis_snapshot_id, NEW.origin_surface)
                       IS DISTINCT FROM
                       (OLD.created_by_id, OLD.question_set_id,
                        OLD.source_analysis_snapshot_id, OLD.origin_surface) THEN
                        RAISE EXCEPTION 'Authoring Conversation creation provenance is immutable'
                            USING ERRCODE = '23514';
                    END IF;
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;
                CREATE TRIGGER leai_authoring_conversation_identity_immutable
                    BEFORE UPDATE OF created_by_id, question_set_id,
                        source_analysis_snapshot_id, origin_surface
                    ON leai_authoringconversation
                    FOR EACH ROW EXECUTE FUNCTION leai_reject_authoring_conversation_identity_update();

                CREATE FUNCTION leai_reject_analysis_chat_owner_update()
                RETURNS trigger AS $$
                BEGIN
                    IF (NEW.course_id, NEW.actor_account_id, NEW.origin_surface)
                       IS DISTINCT FROM
                       (OLD.course_id, OLD.actor_account_id, OLD.origin_surface) THEN
                        RAISE EXCEPTION 'Analysis Chat owner and origin are immutable'
                            USING ERRCODE = '23514';
                    END IF;
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;
                CREATE TRIGGER leai_analysis_chat_owner_immutable
                    BEFORE UPDATE ON leai_analysischatsession
                    FOR EACH ROW EXECUTE FUNCTION leai_reject_analysis_chat_owner_update();

                CREATE FUNCTION leai_reject_analysis_message_parent_update()
                RETURNS trigger AS $$
                BEGIN
                    IF NEW.analysis_chat_session_id IS DISTINCT FROM OLD.analysis_chat_session_id THEN
                        RAISE EXCEPTION 'Analysis message parent is immutable'
                            USING ERRCODE = '23514';
                    END IF;
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;
                CREATE TRIGGER leai_analysis_message_parent_immutable
                    BEFORE UPDATE OF analysis_chat_session_id ON leai_analysischatmessage
                    FOR EACH ROW EXECUTE FUNCTION leai_reject_analysis_message_parent_update();

                CREATE FUNCTION leai_guard_sourced_question_set_course()
                RETURNS trigger AS $$
                BEGIN
                    IF NEW.course_id IS DISTINCT FROM OLD.course_id
                       AND EXISTS (
                           SELECT 1 FROM leai_authoringconversation
                           WHERE question_set_id = OLD.id
                             AND source_analysis_snapshot_id IS NOT NULL
                       ) THEN
                        RAISE EXCEPTION 'Question Set with analysis lineage cannot change course'
                            USING ERRCODE = '23514';
                    END IF;
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;
                CREATE TRIGGER leai_sourced_question_set_course_immutable
                    BEFORE UPDATE OF course_id ON leai_questionset
                    FOR EACH ROW EXECUTE FUNCTION leai_guard_sourced_question_set_course();

                CREATE FUNCTION leai_check_import_record_provenance()
                RETURNS trigger AS $$
                DECLARE run_source text; run_target text; run_type text; map_source text;
                        map_target text; map_model text; map_key text;
                BEGIN
                    IF TG_TABLE_NAME = 'leai_importrecordmap' THEN
                        SELECT source_environment, target_environment, import_run.run_kind
                            INTO run_source, run_target, run_type
                            FROM leai_importrun AS import_run
                            WHERE import_run.id = NEW.first_import_run_id;
                        IF run_source IS NULL OR run_target IS NULL
                           OR run_type <> 'execute'
                           OR NEW.source_environment <> run_source
                           OR NEW.target_environment <> run_target THEN
                            RAISE EXCEPTION 'Import map requires a matching execute run'
                                USING ERRCODE = '23514';
                        END IF;
                    ELSE
                        SELECT source_environment, target_environment, import_run.run_kind
                            INTO run_source, run_target, run_type
                            FROM leai_importrun AS import_run
                            WHERE import_run.id = NEW.import_run_id;
                        IF run_source IS NULL OR
                           (run_type = 'execute' AND NEW.disposition IN ('mapped', 'reused')
                            AND NEW.import_record_map_id IS NULL) THEN
                            RAISE EXCEPTION 'Execute mapping outcome requires a durable map'
                                USING ERRCODE = '23514';
                        END IF;
                        IF NEW.import_record_map_id IS NOT NULL THEN
                            SELECT source_environment, target_environment,
                                   source_model, source_key
                                INTO map_source, map_target, map_model, map_key
                                FROM leai_importrecordmap
                                WHERE id = NEW.import_record_map_id;
                            IF map_source IS NULL
                               OR map_source <> run_source OR map_target <> run_target
                               OR map_model <> NEW.source_model OR map_key <> NEW.source_key THEN
                                RAISE EXCEPTION 'Import outcome must reference its exact source map'
                                    USING ERRCODE = '23514';
                            END IF;
                        END IF;
                    END IF;
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;
                CREATE TRIGGER leai_import_map_run_scope
                    BEFORE INSERT ON leai_importrecordmap
                    FOR EACH ROW EXECUTE FUNCTION leai_check_import_record_provenance();
                CREATE TRIGGER leai_import_outcome_map_scope
                    BEFORE INSERT ON leai_importrecordoutcome
                    FOR EACH ROW EXECUTE FUNCTION leai_check_import_record_provenance();

                CREATE FUNCTION leai_reject_import_run_identity_update()
                RETURNS trigger AS $$
                BEGIN
                    IF (NEW.actor_account_id, NEW.run_kind, NEW.source_environment,
                        NEW.target_environment, NEW.idempotency_key_hash,
                        NEW.manifest_digest, NEW.source_release, NEW.target_release,
                        NEW.migration_set, NEW.contract_version)
                       IS DISTINCT FROM
                       (OLD.actor_account_id, OLD.run_kind, OLD.source_environment,
                        OLD.target_environment, OLD.idempotency_key_hash,
                        OLD.manifest_digest, OLD.source_release, OLD.target_release,
                        OLD.migration_set, OLD.contract_version) THEN
                        RAISE EXCEPTION 'Import Run provenance is immutable'
                            USING ERRCODE = '23514';
                    END IF;
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;
                CREATE TRIGGER leai_import_run_provenance_immutable
                    BEFORE UPDATE ON leai_importrun
                    FOR EACH ROW EXECUTE FUNCTION leai_reject_import_run_identity_update();
            """,
            reverse_sql="""
                DROP TRIGGER IF EXISTS leai_import_run_provenance_immutable ON leai_importrun;
                DROP FUNCTION IF EXISTS leai_reject_import_run_identity_update();
                DROP TRIGGER IF EXISTS leai_import_outcome_map_scope ON leai_importrecordoutcome;
                DROP TRIGGER IF EXISTS leai_import_map_run_scope ON leai_importrecordmap;
                DROP FUNCTION IF EXISTS leai_check_import_record_provenance();
                DROP TRIGGER IF EXISTS leai_sourced_question_set_course_immutable ON leai_questionset;
                DROP FUNCTION IF EXISTS leai_guard_sourced_question_set_course();
                DROP TRIGGER IF EXISTS leai_response_message_append_only ON leai_responsemessage;
                DROP TRIGGER IF EXISTS leai_analysis_message_parent_immutable ON leai_analysischatmessage;
                DROP FUNCTION IF EXISTS leai_reject_analysis_message_parent_update();
                DROP TRIGGER IF EXISTS leai_analysis_chat_owner_immutable ON leai_analysischatsession;
                DROP FUNCTION IF EXISTS leai_reject_analysis_chat_owner_update();
                DROP TRIGGER IF EXISTS leai_authoring_conversation_identity_immutable ON leai_authoringconversation;
                DROP FUNCTION IF EXISTS leai_reject_authoring_conversation_identity_update();
                DROP TRIGGER IF EXISTS leai_authoring_source_snapshot_same_course ON leai_authoringconversation;
                DROP FUNCTION IF EXISTS leai_check_authoring_snapshot_course();
                DROP TRIGGER IF EXISTS leai_analysis_citation_same_course ON leai_analysiscitation;
                DROP FUNCTION IF EXISTS leai_check_analysis_citation_course();
                DROP TRIGGER IF EXISTS leai_analysis_scope_same_course ON leai_analysisscopeoccurrence;
                DROP FUNCTION IF EXISTS leai_check_analysis_scope_course();
                DROP TRIGGER IF EXISTS leai_analysis_scope_frozen_after_message ON leai_analysisscopeoccurrence;
                DROP FUNCTION IF EXISTS leai_reject_analysis_scope_after_message();
                DROP TRIGGER IF EXISTS leai_analysis_message_lock_parent ON leai_analysischatmessage;
                DROP FUNCTION IF EXISTS leai_lock_analysis_chat_for_message_insert();
                DROP TRIGGER IF EXISTS leai_importrun_uuid_immutable ON leai_importrun;
                DROP TRIGGER IF EXISTS leai_auditevent_uuid_immutable ON leai_auditevent;
                DROP FUNCTION IF EXISTS leai_reject_task6_public_uuid_update();
                DROP TRIGGER IF EXISTS leai_import_record_map_append_only ON leai_importrecordmap;
                DROP TRIGGER IF EXISTS leai_import_record_outcome_append_only ON leai_importrecordoutcome;
                DROP TRIGGER IF EXISTS leai_audit_event_append_only ON leai_auditevent;
                DROP TRIGGER IF EXISTS leai_analysis_citation_append_only ON leai_analysiscitation;
                DROP TRIGGER IF EXISTS leai_analysis_snapshot_append_only ON leai_analysissnapshot;
                DROP FUNCTION IF EXISTS leai_reject_task6_append_only();
                ALTER TABLE leai_auditevent DROP CONSTRAINT IF EXISTS leai_audit_metadata_bounded_object;
                ALTER TABLE leai_importrun ALTER COLUMN public_id DROP DEFAULT;
                ALTER TABLE leai_auditevent ALTER COLUMN event_id DROP DEFAULT;
            """,
        ),
    ]
