# Generated by Django 4.2.7 on 2026-09-22 20:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('leai', '0008_analysis_governance'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductUsageEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('event_type', models.CharField(choices=[('survey_loaded', 'Survey Loaded'), ('output_download_attempted', 'Output Download Attempted')], max_length=32)),
                ('event_version', models.PositiveSmallIntegerField()),
                ('response_phase', models.CharField(blank=True, choices=[('first_load', 'First Load'), ('reload_before_response', 'Reload Before Response'), ('resume_during_response', 'Resume During Response'), ('reload_after_completion', 'Reload After Completion')], max_length=32, null=True)),
                ('output_kind', models.CharField(blank=True, choices=[('certificate', 'Certificate'), ('completed_response', 'Completed Response')], max_length=32, null=True)),
                ('outcome', models.CharField(blank=True, choices=[('succeeded', 'Succeeded'), ('not_ready', 'Not Ready'), ('closed', 'Closed'), ('generation_failed', 'Generation Failed')], max_length=32, null=True)),
                ('app_build_sha', models.CharField(max_length=64)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('response_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usage_events', to='leai.responsesession')),
            ],
        ),
        migrations.AddConstraint(
            model_name='productusageevent',
            constraint=models.CheckConstraint(check=models.Q(('event_version', 1)), name='leai_usage_event_version_one'),
        ),
        migrations.AddConstraint(
            model_name='productusageevent',
            constraint=models.CheckConstraint(check=models.Q(('app_build_sha__regex', '^[0-9a-f]{7,64}$')), name='leai_usage_event_build_sha_valid'),
        ),
        migrations.AddConstraint(
            model_name='productusageevent',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('event_type', 'survey_loaded'), ('outcome__isnull', True), ('output_kind__isnull', True), ('response_phase__in', ['first_load', 'reload_before_response', 'resume_during_response', 'reload_after_completion']), ('response_phase__isnull', False)), models.Q(('event_type', 'output_download_attempted'), ('outcome__in', ['succeeded', 'not_ready', 'closed', 'generation_failed']), ('outcome__isnull', False), ('output_kind__in', ['certificate', 'completed_response']), ('output_kind__isnull', False), ('response_phase__isnull', True)), _connector='OR'), name='leai_usage_event_exact_shape'),
        ),
        migrations.RunSQL(
            sql="""
                ALTER TABLE leai_productusageevent
                    ALTER COLUMN event_id SET DEFAULT gen_random_uuid();

                CREATE FUNCTION leai_guard_usage_event_insert()
                RETURNS trigger AS $$
                DECLARE parent_source text;
                DECLARE parent_consent boolean;
                BEGIN
                    SELECT source, research_consent
                    INTO parent_source, parent_consent
                    FROM leai_responsesession
                    WHERE id = NEW.response_session_id
                    FOR SHARE;

                    IF parent_source IS DISTINCT FROM 'student'
                       OR parent_consent IS DISTINCT FROM TRUE THEN
                        RAISE EXCEPTION 'Product usage requires a consented student ResponseSession'
                            USING ERRCODE = '23514';
                    END IF;
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER leai_usage_event_parent_consent
                    BEFORE INSERT ON leai_productusageevent
                    FOR EACH ROW EXECUTE FUNCTION leai_guard_usage_event_insert();

                CREATE FUNCTION leai_reject_usage_event_mutation()
                RETURNS trigger AS $$
                BEGIN
                    RAISE EXCEPTION 'LEAI ProductUsageEvent is append-only'
                        USING ERRCODE = '23514';
                END;
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER leai_usage_event_append_only
                    BEFORE UPDATE OR DELETE ON leai_productusageevent
                    FOR EACH ROW EXECUTE FUNCTION leai_reject_usage_event_mutation();
            """,
            reverse_sql="""
                DROP TRIGGER leai_usage_event_append_only ON leai_productusageevent;
                DROP FUNCTION leai_reject_usage_event_mutation();
                DROP TRIGGER leai_usage_event_parent_consent ON leai_productusageevent;
                DROP FUNCTION leai_guard_usage_event_insert();
                ALTER TABLE leai_productusageevent ALTER COLUMN event_id DROP DEFAULT;
            """,
        ),
    ]
