# Generated by Django 5.2.17 on 2026-09-27 22:58

import uuid

from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone


def backfill_chat_session_values(apps, schema_editor):
    ChatSession = apps.get_model("leai", "AnalysisChatSession")
    alias = schema_editor.connection.alias
    for session in ChatSession.objects.using(alias).filter(public_id__isnull=True).iterator():
        ChatSession.objects.using(alias).filter(pk=session.pk).update(public_id=uuid.uuid4())
    for session in ChatSession.objects.using(alias).filter(updated_at__isnull=True).iterator():
        ChatSession.objects.using(alias).filter(pk=session.pk).update(
            updated_at=session.created_at or timezone.now()
        )


def update_chat_scope_trigger(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            CREATE OR REPLACE FUNCTION leai_reject_analysis_scope_after_message()
            RETURNS trigger AS $$
            DECLARE scope_chat_id bigint; moved_chat_id bigint;
            BEGIN
                -- Scope is an append-only source list once a conversation has started.
                -- New sources affect future turns while preserving prior messages/citations.
                IF TG_OP = 'INSERT' THEN
                    RETURN NEW;
                END IF;
                scope_chat_id := OLD.analysis_chat_session_id;
                IF TG_OP = 'UPDATE' THEN
                    moved_chat_id := NEW.analysis_chat_session_id;
                END IF;
                PERFORM id FROM leai_analysischatsession
                    WHERE id IN (scope_chat_id, moved_chat_id)
                    ORDER BY id FOR UPDATE;
                IF EXISTS (
                    SELECT 1 FROM leai_analysischatmessage
                    WHERE analysis_chat_session_id = scope_chat_id
                ) OR (moved_chat_id IS NOT NULL AND EXISTS (
                    SELECT 1 FROM leai_analysischatmessage
                    WHERE analysis_chat_session_id = moved_chat_id
                )) THEN
                    RAISE EXCEPTION 'Analysis scope entries cannot be edited after first message'
                        USING ERRCODE = '23514';
                END IF;
                IF TG_OP = 'DELETE' THEN
                    RETURN OLD;
                END IF;
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;
            """
        )


def restore_chat_scope_trigger(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            CREATE OR REPLACE FUNCTION leai_reject_analysis_scope_after_message()
            RETURNS trigger AS $$
            DECLARE scope_chat_id bigint; moved_chat_id bigint;
            BEGIN
                IF TG_OP = 'INSERT' THEN
                    scope_chat_id := NEW.analysis_chat_session_id;
                ELSIF TG_OP = 'DELETE' THEN
                    scope_chat_id := OLD.analysis_chat_session_id;
                ELSE
                    scope_chat_id := OLD.analysis_chat_session_id;
                    moved_chat_id := NEW.analysis_chat_session_id;
                END IF;
                PERFORM id FROM leai_analysischatsession
                    WHERE id IN (scope_chat_id, moved_chat_id)
                    ORDER BY id FOR UPDATE;
                IF EXISTS (
                    SELECT 1 FROM leai_analysischatmessage
                    WHERE analysis_chat_session_id = scope_chat_id
                ) OR (moved_chat_id IS NOT NULL AND EXISTS (
                    SELECT 1 FROM leai_analysischatmessage
                    WHERE analysis_chat_session_id = moved_chat_id
                )) THEN
                    RAISE EXCEPTION 'Analysis scope is frozen after first message'
                        USING ERRCODE = '23514';
                END IF;
                IF TG_OP = 'DELETE' THEN
                    RETURN OLD;
                END IF;
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;
            """
        )


class Migration(migrations.Migration):

    dependencies = [
        ('leai', '0013_disable_forced_password_rotation'),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="anonymous_matching_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="analysischatsession",
            name="public_id",
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="analysischatsession",
            name="title",
            field=models.CharField(default="New chat", max_length=120),
        ),
        migrations.AddField(
            model_name="analysischatsession",
            name="prompt_override",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="analysischatsession",
            name="archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="analysischatsession",
            name="updated_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.RunPython(backfill_chat_session_values, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="analysischatsession",
            name="public_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="analysischatsession",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="analysiscitation",
            name="evidence_quote",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddConstraint(
            model_name="analysischatsession",
            constraint=models.CheckConstraint(
                check=~models.Q(title=""), name="leai_analysis_chat_title_nonempty"
            ),
        ),
        migrations.CreateModel(
            name="DomainJob",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("job_type", models.CharField(choices=[("feedback_chat_turn", "Feedback Chat turn")], max_length=32)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("running", "Running"), ("completed", "Completed"), ("failed", "Failed")], default="pending", max_length=16)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("payload", models.JSONField(default=dict)),
                ("result", models.JSONField(blank=True, null=True)),
                ("error_code", models.CharField(blank=True, max_length=64, null=True)),
                ("lease_token", models.UUIDField(blank=True, null=True)),
                ("lease_expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("actor_account", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="domain_jobs", to="leai.instructoraccount")),
                ("course", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="domain_jobs", to="leai.course")),
            ],
        ),
        migrations.AddConstraint(
            model_name="domainjob",
            constraint=models.CheckConstraint(check=models.Q(job_type="feedback_chat_turn"), name="leai_domain_job_type_valid"),
        ),
        migrations.AddConstraint(
            model_name="domainjob",
            constraint=models.CheckConstraint(check=models.Q(status__in=["pending", "running", "completed", "failed"]), name="leai_domain_job_status_valid"),
        ),
        migrations.AddConstraint(
            model_name="domainjob",
            constraint=models.CheckConstraint(check=models.Q(attempts__lte=5), name="leai_domain_job_attempts_bounded"),
        ),
        migrations.AddConstraint(
            model_name="domainjob",
            constraint=models.CheckConstraint(
                check=(models.Q(status="running", lease_token__isnull=False, lease_expires_at__isnull=False)
                       | models.Q(status__in=["pending", "completed", "failed"], lease_token__isnull=True, lease_expires_at__isnull=True)),
                name="leai_domain_job_lease_shape_valid",
            ),
        ),
        migrations.CreateModel(
            name="ResponseSessionMatchSignal",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("device_key_digest", models.CharField(blank=True, max_length=64, null=True)),
                ("fingerprint_digest", models.CharField(blank=True, max_length=64, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("response_session", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="matching_signal", to="leai.responsesession")),
            ],
        ),
        migrations.AddConstraint(
            model_name="responsesessionmatchsignal",
            constraint=models.CheckConstraint(
                check=models.Q(device_key_digest__isnull=False) | models.Q(fingerprint_digest__isnull=False),
                name="leai_matching_signal_has_digest",
            ),
        ),
        migrations.AddConstraint(
            model_name="responsesessionmatchsignal",
            constraint=models.CheckConstraint(
                check=models.Q(device_key_digest__isnull=True) | models.Q(device_key_digest__regex=r"^[0-9a-f]{64}$"),
                name="leai_matching_signal_device_digest_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="responsesessionmatchsignal",
            constraint=models.CheckConstraint(
                check=models.Q(fingerprint_digest__isnull=True) | models.Q(fingerprint_digest__regex=r"^[0-9a-f]{64}$"),
                name="leai_matching_signal_fingerprint_digest_valid",
            ),
        ),
        migrations.RunPython(update_chat_scope_trigger, restore_chat_scope_trigger),
    ]
