# Generated by Django 5.2.17 on 2026-09-28 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leai', '0014_feedback_chat_analyzer_base'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='domainjob',
            name='leai_domain_job_type_valid',
        ),
        migrations.AlterField(
            model_name='domainjob',
            name='job_type',
            field=models.CharField(choices=[('feedback_chat_turn', 'Feedback Chat turn'), ('authoring_ai_run', 'Authoring AI run')], max_length=32),
        ),
        migrations.AddConstraint(
            model_name='domainjob',
            constraint=models.CheckConstraint(condition=models.Q(('job_type__in', ['feedback_chat_turn', 'authoring_ai_run'])), name='leai_domain_job_type_valid'),
        ),
    ]
