"""
Django settings for guiidatapipelines project.

Generated by 'django-admin startproject' using Django 3.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import os
from pathlib import Path
import dj_database_url
import django_on_heroku as django_heroku
from django.core.exceptions import ImproperlyConfigured

try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-n=tqs=w%ta2ejbii@g*r!!_)n02bj)@&i7d6zyy%mz5skvn+ke'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    "leai.apps.LeaiConfig",
    "datapipeline.apps.DatapipelineConfig",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = 'guiidatapipelines.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'guiidatapipelines.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': 'ciba',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files (user uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
django_heroku.settings(locals())

# The canonical LEAI API is opt-in per deployment. The legacy Django runtime
# stays local until QA and Production provide separately reviewed identities.
_LEAI_HOSTED_RUNTIME = any(os.environ.get(key) for key in (
    "DYNO", "HEROKU_APP_NAME", "K_SERVICE", "RENDER", "FLY_APP_NAME",
))
LEAI_ENVIRONMENT = os.environ.get("LEAI_ENVIRONMENT", "" if _LEAI_HOSTED_RUNTIME else "local")
LEAI_BUILD_ID = os.environ.get("LEAI_BUILD_ID", "" if _LEAI_HOSTED_RUNTIME else "local-backend")

# The existing QA and Production apps share a PostgreSQL database but own
# different schemas. Pin the connection before any release-phase migration:
# an unqualified Django table name must never fall back to public in QA.
if _LEAI_HOSTED_RUNTIME:
    if LEAI_ENVIRONMENT not in ("qa", "production"):
        raise ImproperlyConfigured("Hosted runtime requires LEAI_ENVIRONMENT=qa or production")
    expected_schema = "leai_qa" if LEAI_ENVIRONMENT == "qa" else "public"
    if os.environ.get("LEAI_DB_SCHEMA") != expected_schema:
        raise ImproperlyConfigured(
            f"{LEAI_ENVIRONMENT} requires LEAI_DB_SCHEMA={expected_schema}"
        )
    DATABASES["default"].setdefault("OPTIONS", {})["options"] = (
        f"-c search_path={expected_schema}"
    )

# django_on_heroku sets ALLOWED_HOSTS to ["*"] and uses SECRET_KEY only when
# present. Apply the actual security boundary after that helper runs.
if _LEAI_HOSTED_RUNTIME:
    SECRET_KEY = os.environ.get("SECRET_KEY", "")
    if len(SECRET_KEY) < 50 or SECRET_KEY.startswith("django-insecure-"):
        raise ImproperlyConfigured("Hosted runtime requires a strong SECRET_KEY")
    hosts = os.environ.get("DJANGO_ALLOWED_HOSTS", "")
    if not hosts:
        hosts = os.environ.get("HEROKU_APP_DEFAULT_DOMAIN_NAME", "")
    ALLOWED_HOSTS = [host.strip() for host in hosts.split(",") if host.strip()]
    if not ALLOWED_HOSTS or any("*" in host or "/" in host or ":" in host for host in ALLOWED_HOSTS):
        raise ImproperlyConfigured("Hosted runtime requires explicit DJANGO_ALLOWED_HOSTS")
    DEBUG = False
    SECURE_SSL_REDIRECT = True
    if os.environ.get("DYNO") or os.environ.get("HEROKU_APP_NAME"):
        SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_HSTS_SECONDS = 31536000
    SESSION_COOKIE_SECURE = True
    SESSION_COOKIE_HTTPONLY = True
    SESSION_COOKIE_SAMESITE = "Lax"
    CSRF_COOKIE_SECURE = True
    CSRF_COOKIE_HTTPONLY = True
    CSRF_COOKIE_SAMESITE = "Lax"
    SECURE_CONTENT_TYPE_NOSNIFF = True
else:
    ALLOWED_HOSTS = ["localhost", "127.0.0.1", "[::1]", "testserver"]

# Django owns the browser credential. The frontend receives only session metadata
# and a masked CSRF token; no instructor bearer token is exposed to JavaScript.
SESSION_ENGINE = "django.contrib.sessions.backends.db"
SESSION_COOKIE_NAME = "__Host-leai-session" if _LEAI_HOSTED_RUNTIME else "leai-session"
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_PATH = "/"
SESSION_COOKIE_DOMAIN = None
SESSION_COOKIE_AGE = 3600
CSRF_COOKIE_NAME = "__Host-leai-csrf" if _LEAI_HOSTED_RUNTIME else "leai-csrf"
CSRF_COOKIE_HTTPONLY = True
CSRF_FAILURE_VIEW = "leai.api.instructor_auth.csrf_failure"

# Opt in only for the new combined LEAI release. The old backend deployment is
# not silently repurposed. The build directory contains public Vite output only.
LEAI_SERVE_FRONTEND = os.environ.get("LEAI_SERVE_FRONTEND") == "1"
if LEAI_SERVE_FRONTEND:
    from leai.hosting import frontend_headers, validate_frontend_bundle
    LEAI_FRONTEND_ROOT = os.environ.get("LEAI_FRONTEND_ROOT", os.path.join(BASE_DIR, "frontend_dist"))
    validate_frontend_bundle(LEAI_FRONTEND_ROOT, LEAI_ENVIRONMENT, LEAI_BUILD_ID)
    ROOT_URLCONF = "leai.web_urls"
    WHITENOISE_ROOT = LEAI_FRONTEND_ROOT
    WHITENOISE_INDEX_FILE = True
    WHITENOISE_ADD_HEADERS_FUNCTION = frontend_headers
    WHITENOISE_ALLOW_ALL_ORIGINS = False

# CORS is an origin boundary, not a URL-path boundary. Both Pages deployments
# share the same approved origin; local Vite is allowed only in local mode.
CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOWED_ORIGINS = ["https://guii-lab.github.io"]
if LEAI_SERVE_FRONTEND:
    CORS_ALLOWED_ORIGINS = []  # Browser API calls are same-origin.
if LEAI_ENVIRONMENT == "local" and not LEAI_SERVE_FRONTEND:
    CORS_ALLOWED_ORIGINS += [
        "http://127.0.0.1:5173",
        "http://localhost:5173",
        "http://127.0.0.1:4173",
        "http://localhost:4173",
        "http://127.0.0.1:8080",
        "http://localhost:8080",
    ]
